### ISSUE TITLE
Initial infrastructure changes

### ISSUE THREAD

**Issue by satra** [dandi/dandi-api#1]
- [x] strip away girder connections
- switch to github actions for integration
- [x] setup a pytest framework (data + code) to simulate client testing of the api

**Comment by yarikoptic** [comment]
marked two which I think are done.  not sure if switch of CI is really needed.  Will leave to @satra to decide if issue is sufficiently handled.

**Comment by satra** [comment]
let's keep the CI switch aside. just that it is easier for new people to come and see consistency across a project. so you don't need to mental gymnastics to go from one part of the project to another. i'm fine with punting the CI change later, but would be good to converge.
