### ISSUE TITLE
Use / to separate sha256 when storing blobs

### ISSUE THREAD

**Issue by dchiquito** [dandi/dandi-api#107]
As per #97 we should include some slashes in the sha256 checksum used when storing the blobs so they are rendered in subdirectories by clients, rather than a single mass of blobs.
```
2cf24dba5fb0a30e26e83b2ac5b9e29e1b161e5c1fa7425e73043362938b9824
2cf/24d/ba5fb0a30e26e83b2ac5b9e29e1b161e5c1fa7425e73043362938b9824
```

**Comment by yarikoptic** [comment]
FWIW: I cannot come up with a use-case whenever extraction of prefix (instead of still keeping it in the end "filename" as well, thus duplicating) from the checksum would lead to suboptimality of some kind.

**Comment by dchiquito** [comment]
@yarikoptic Are you saying you would prefer this instead?
```
2cf24dba5fb0a30e26e83b2ac5b9e29e1b161e5c1fa7425e73043362938b9824
2cf/24d/2cf24dba5fb0a30e26e83b2ac5b9e29e1b161e5c1fa7425e73043362938b9824
```

**Comment by yarikoptic** [comment]
yes, that was my initial idea.  But, as I said, I do not see yet immediate benefit (besides being able to find e.g. file by checksum easier with `find` etc)
