### ISSUE TITLE
Validate asset metadata before upload

### ISSUE THREAD

**Issue by dchiquito** [dandi/dandi-api#117]
>  We will eventually add the CLI as a dependency and use it to validate the asset metadata as well

> we should do that at the stage of initiating the upload (based on metadata provided), validation of the blob should indeed just verify checksum only -- it would be a boomer if lengthy upload "fails" if some metadata apparently is not kosher according to server side decision making.  I think we are doomed to trust client to provide "untainted" metadata upon initiation of the upload.

_Originally posted by @yarikoptic in https://github.com/dandi/dandi-api/pull/104#r576526761_

**Comment by yarikoptic** [comment]
note: unfortunately with #150 implemented #156 we went a little "off" in that uploads are to be initiated at the `/blobs` level so no metadata is provided.  But as discussed in #150 (somewhere) we could later "move" to initiate uploads from `/assets/...` level thus providing full metadata records and validating them before upload is even initiated.
I think "metadata validation" would be one of the next topics but not yet sure if part of "migration", thus not allocating it to any milestone/project and will leave that to @satra et al

**Comment by waxlamp** [comment]
I think this is either done or moot, with validation becoming a part of the publish workflow, and with all validation logic living in dandischema.
