### ISSUE TITLE
api server landing page and api url.

### ISSUE THREAD

**Issue by satra** [dandi/dandi-api#119]
for the api endpoint currently `api.dandiarchive.org` returns a 404.  it would be nice if either that returned reference documentation or redirected to the api doc location. 

also the current api url looks like this. can we remove the second `api`

`https://api.dandiarchive.org/api/`

this can happen after the current issues are sorted out but before migrating datasets over for good so that all download url's are consistent.

also just an fyi that github has moved from versioned URLs for their REST API to accept headers for version.

**Comment by yarikoptic** [comment]
very much related : #36

**Comment by waxlamp** [comment]
@satra, I've split off the top level 404 issue into #166, but unfortunately we can't remove that second `api/` very easily, since Django contains other top level paths such as `admin/`, etc., that need to be walled off from the API endpoints.

**Comment by satra** [comment]
who is doing the load balancing for the api requests? can we do it through a proxy?

**Comment by waxlamp** [comment]
> who is doing the load balancing for the api requests? can we do it through a proxy?

I assume this is handled within Heroku somehow. @brianhelba will probably know the answer.

**Comment by brianhelba** [comment]
Yes, Heroku does load balancing (trivially in this case, since we only have a single dyno backend) and SSL termination. Adding another proxy to this architecture would be counter to the purpose of Heroku.
