### ISSUE TITLE
uploading of large files runs out of disk space

### ISSUE THREAD

**Issue by yarikoptic** [dandi/dandi-api#121]
you can see below that files > 100GB in size reported an error... I thought that there is no point in time when they touch a disk and everything is streamed for validation (checksum, no metadata validation as extracted from the files yet)
```
PATH                                                                        SIZE        ERRORS         UPLOAD STATUS                MESSAGE                                                                                                    CURRENT
sub-YutaMouse33/sub-YutaMouse33_ses-YutaMouse33-150218_behavior+ecephys.nwb 11.9 GB        3                  skipped               failed validation
sub-YutaMouse33/sub-YutaMouse33_ses-YutaMouse33-150219_behavior+ecephys.nwb 19.6 GB        0             100% done                                                                                                                             19555288402
sub-YutaMouse33/sub-YutaMouse33_ses-YutaMouse33-150220_behavior+ecephys.nwb 22.9 GB        0             100% done                                                                                                                             22887043393
sub-YutaMouse33/sub-YutaMouse33_ses-YutaMouse33-150221_behavior+ecephys.nwb 28.9 GB        0             100% done                                                                                                                             28923100908
sub-YutaMouse33/sub-YutaMouse33_ses-YutaMouse33-150226_behavior+ecephys.nwb 27.5 GB        0             100% done                                                                                                                             27482210179
sub-YutaMouse33/sub-YutaMouse33_ses-YutaMouse33-150222_behavior+ecephys.nwb 160.5 GB       0             100% ERROR                 Server-side asset validation failed!  Error reported: Internal error: [Errno 28] No space left on device   160536501381
sub-YutaMouse33/sub-YutaMouse33_ses-YutaMouse33-150223_behavior+ecephys.nwb 143.5 GB       0             100% ERROR                 Server-side asset validation failed!  Error reported: Internal error: [Errno 28] No space left on device   143508573281
sub-YutaMouse33/sub-YutaMouse33_ses-YutaMouse33-150224_behavior+ecephys.nwb 143.8 GB       0             100% ERROR                 Server-side asset validation failed!  Error reported: Internal error: [Errno 28] No space left on device   143800359068
sub-YutaMouse33/sub-YutaMouse33_ses-YutaMouse33-150225_behavior+ecephys.nwb 97.5 GB        0             100% done                                                                                                                             97467147698
Summary:                                                                    656.1 GB 1 with errors  52.6 MB/s 1 skipped             1 failed validation
                                                                                                              5 done                3 Server-side asset validation failed!  Error reported: Internal error: [Errno 28] No space left on device
                                                                                                              3 ERROR
2021-02-18 23:02:23,168 [    INFO] Logs saved in /home/yoh/.cache/dandi-cli/log/20210219003818Z-12291.log
```

edit: forgot to list that it is the 000003 -- so fix could be verified.  Feel welcome to remove first what is already there or just `dandi upload --existing force`

**Comment by dchiquito** [comment]
I see this error in Sentry popping up at around the same time: `ssl.SSLError: [SSL: PROTOCOL_IS_SHUTDOWN] protocol is shutdown`. Looks like it started happening on Feb 18 10:23 PM EST and happened occasionally until 7AM.

**Comment by waxlamp** [comment]
@yarikoptic, would you mind posting `/home/yoh/.cache/dandi-cli/log/20210219003818Z-12291.log` in this thread?

**Comment by yarikoptic** [comment]
unfortunately that particular log is not anyhow more informative:
```
$> cat /home/yoh/.cache/dandi-cli/log/20210219003818Z-12291.log
2021-02-18T19:38:18-0500 [INFO    ] dandi [META] sys.argv = ['/home/yoh/miniconda3/bin/dandi', '--pdb', 'upload', '-i', 'dandi-api', 'sub-YutaMouse33']
2021-02-18T19:38:18-0500 [INFO    ] dandi [META] os.getcwd() = /mnt/backup/dandi/dandisets/000003
2021-02-18T19:38:21-0500 [INFO    ] dandi Found 9 files to consider
2021-02-18T23:02:23-0500 [INFO    ] dandi Logs saved in /home/yoh/.cache/dandi-cli/log/20210219003818Z-12291.log
```
I am rerunning now for one of those files (although may be I need multiple to trigger):
```
drogon:/mnt/backup/dandi/dandisets/000003
$> DANDI_DEVEL=1 dandi -l 1 --pdb upload -i dandi-api --devel-debug sub-YutaMouse33/sub-YutaMouse33_ses-YutaMouse33-150222_behavior+ecephys.nwb
...
```
and will post hopefully more debug output from dandi-cli -- but what do you expect to see there, since I doubt there is more than `Error reported: Internal error: [Errno 28] No space left on device` returned from the server

**Comment by yarikoptic** [comment]
FWIW, upload of a single large file went ok.  I will not re-bombard with large files with overwrite -- but may be blobs already there somehow, for `sub-YutaMouse33_ses-YutaMouse33-150222_behavior+ecephys.nwb` it skipped upload and went into `validation` right away... let's see what happens

**Comment by yarikoptic** [comment]
eh, we need to "enrich" logging on `dandi-cli` side: https://github.com/dandi/dandi-cli/issues/410 but I wonder if may be `dandi-api` should also, at least for now or may be forever log whenever it returns failed validation result records.  This way we might have a better chance to provide user support whenever people would report that their uploads failed due to failed validation.  I have tried to identify possible reason for that for `c760c9abc22a0b114e45b3aa1b66ecbb53c8106b247a9b8069162651be243887` upload but papertrail did not give any useful hints.

**Comment by dchiquito** [comment]
#127 should help with that.

**Comment by jwodder** [comment]
I just encountered this while uploading the `sub-YutaMouse33` folder.  Four of the smaller assets passed validation, and then validation failed for the other four with "No space left on device."  [The logs from the upload session are here.](https://gist.github.com/jwodder/157b76286df567fbdc12492cd6393312)

**Comment by dchiquito** [comment]
When calculating the checksum in the validate task, we download the file in small chunks to avoid using too much memory. Unfortunately, the boto3 client is used internally, and apparently it is allocating a file handle for each little download. The `No space left on device` is actually referring to file handles, not space.

I can easily make the chunks 1024 times as large, which would resolve the problem for this scale of data. Since we are currently having trouble with 100s of GB, this would delay problems until we are uploading 100s of TB. I will see what I can do about solving this more permanently.

**Comment by dchiquito** [comment]
Ah, the boto3 client is using `tempfile.SpooledTemporaryFile` to download the entire file, then serving it up in little chunks at the tasks request. I'm looking into using internal methods to download in bits rather than using this temporary cache, which clearly will not work.

**Comment by satra** [comment]
for the moment i think for relatively small datasets it's fine to point at our public bucket, but all network access will cost since the data are coming out of AWS. we should switch to the public bucket as soon as possible to minimize this cost.

**Comment by dchiquito** [comment]
@jwodder I just merged a fix to actually stream the blobs when calculating the checksum, can you kick off a big upload to verify that it's fixed?

**Comment by jwodder** [comment]
@dchiquito Does it need to be an upload of new assets, or is rerunning the post-upload validation for previously-uploaded assets acceptable?  Because I've started the latter.

**Comment by dchiquito** [comment]
That is sufficient, I see validation has begun in the server logs. :crossed_fingers:

**Comment by dchiquito** [comment]
I haven't heard any more problems with this, so I'm closing.
