### ISSUE TITLE
status "messages" per blob/asset/dandiset

### ISSUE THREAD

**Issue by yarikoptic** [dandi/dandi-api#123]
A somewhat long term item, but we will need to provide status updates and errors reporting for assets etc.  Inspired by needs in #122 . Just throwing ideas here, in hope that some might come useful ;)

- may be would want different levels of messages such as INFO (validation finished) and ERROR (invalid checksum, failing metadata check, etc)
- we should define specific types/codes of messages (`INFO_validation_finished`, `ERROR_checksum`, etc) with a record to compliment (e.g. for `ERROR_metadata` would be a list of errors for metadata checks)
- Relates to a "status" of a thing (blob, asset, dandiset), so web ui might gain `status` column which would provide an "alert" icon if any errors (for a dandiset or asset, depending on the view)
- Such messages, when new, should be sent out to owners of the corresponding dandisets (thus the "message" record should have a field which announces if it was already "notified"). Probably bundled (e.g. "in the past hour") instead of individual ones
- Since asset UUID is mutable ATM, it complicates a bit handling of possibly already existing messages -- but I guess we could remove all "asset" messages upon any change to the asset...
- Messages for a blob of an asset would be "joined" with messages for the asset dynamically (so if asset changes its blob), similarly messages for dandiset with messages for assets and corresponding blobs.

**Comment by waxlamp** [comment]
I believe this is covered by dandiset-level and asset-level validation. Re-open if this specific proposal is still needed.
