### ISSUE TITLE
ssl.SSLError: [SSL: PROTOCOL_IS_SHUTDOWN] protocol is shutdown (_ssl.c:2474)

### ISSUE THREAD

**Issue by yarikoptic** [dandi/dandi-api#125]
heroku log is full of those and I believe those were present in sentry reports as well.  ramifications of those aren't known to me but they cannot be "right"

**Comment by waxlamp** [comment]
Might be related to #121.

**Comment by mgrauer** [comment]
Let's leave this for now until we figure it out. So far it seems to be correlated with out of memory errors, which we should hopefully be resolving soon.

Once validation is stable, we can downgrade this from severity-important if it is still happening or close it out.

**Comment by waxlamp** [comment]
I believe this has been solved. If the error recurs, please re-open this issue.
