### ISSUE TITLE
database backup

### ISSUE THREAD

**Issue by satra** [dandi/dandi-api#126]
- is the database backed up somewhere?
- is there a checksum of the api repo stored in the database somewhere so we can match which version was deployed with the database?

- and as a thought experiment could we bring the api server back online on say on google cloud or aws?

**Comment by dchiquito** [comment]
* Yes, Heroku has a very robust postgres backup scheme that allows snapshots and rollbacks.
* No, but it's not something that isn't required operationally at the moment. The API server tracks the `master` branch, so any redeployments would just pull from `master`.
* It's absolutely possible with a sufficient application of time and effort. Girder 4 recommends the Terraform/Heroku stack, so we are currently on the path of least resistance. We can always deviate from that path, at the cost of man-hours.
