### ISSUE TITLE
Process running mem=1174M(114.7%)  Error R14 (Memory quota exceeded)

### ISSUE THREAD

**Issue by yarikoptic** [dandi/dandi-api#133]
From appearance it is not critical since they are not followed by errors typically, although I do observe a single #125 following a recent one of those

**Comment by yarikoptic** [comment]
not sure if still the case (do not have eyes on the logs) but since dandi-api people do not worry, I would not either ;-)

**Comment by satra** [comment]
@dchiquito - seeing a lot of these worker errors again with the dataset i'm currently uploading. 

here is a timestamp if you wanted to check:
```
Jul 12 20:14:45 dandi-api heroku/worker.1 Process running mem=1269M(124.0%)
Jul 12 20:14:45 dandi-api heroku/worker.1 Error R14 (Memory quota exceeded)
```

**Comment by waxlamp** [comment]
I think the underlying cause of this issue has since been resolved, but re-open if not.
