### ISSUE TITLE
GET /blobs/{sha256}/download endpoint

### ISSUE THREAD

**Issue by yarikoptic** [dandi/dandi-api#135]
`GET /blobs/{sha256}` could provide the record with the size (if already in the table, didn't check the schema) and all the modified/created time stamps

It is needed because asset UUID (for a draft version) is no longer a guarantee for getting a precise known version of an asset.  With direct access to the blob it would make it possible to access an exact version.

PS edit 1: depending on a decision to be made in https://github.com/dandi/dandisets/issues/34 might become a blocker to killing girder blobstore (part of a migration, but could be done after)

**Comment by waxlamp** [comment]
@yarikoptic can you clarify whether this is still needed? It sounds like you are asking for a content-addressable store for the blobs, but I'm not clear on why accessing a dandiset's asset blobs via asset IDs is a problem.
