### ISSUE TITLE
publish of 000008 leads to [CRITICAL] WORKER TIMEOUT (pid:20)

### ISSUE THREAD

**Issue by yarikoptic** [dandi/dandi-api#137]
web UI shows the release ok, and seems to browse... didn't compare dumps of assets yet, but spotted following in papertrail

```

Feb 25 19:55:09 dandi-api heroku/router at=error code=H12 desc="Request timeout" method=POST path="/api/dandisets/000008/versions/draft/publish/" host=api.dandiarchive.org request_id=833a7c15-297f-4f9e-9f4d-55f99742d8fb fwd="76.24.253.1" dyno=web.1 connect=1ms service=30002ms status=503 bytes=0 protocol=https
Feb 25 19:55:09 dandi-api app/web.1 [2021-02-26 03:55:09 +0000] [4] [CRITICAL] WORKER TIMEOUT (pid:10)
Feb 25 19:56:08 dandi-api heroku/router at=error code=H12 desc="Request timeout" method=POST path="/api/dandisets/000008/versions/draft/publish/" host=api.dandiarchive.org request_id=8991ff27-2bc1-4b50-b4d9-499954673e52 fwd="76.24.253.1" dyno=web.1 connect=1ms service=30001ms status=503 bytes=0 protocol=https
Feb 25 19:56:09 dandi-api app/web.1 [2021-02-26 03:56:08 +0000] [4] [CRITICAL] WORKER TIMEOUT (pid:9)
Feb 25 19:56:21 dandi-api heroku/router at=error code=H12 desc="Request timeout" method=POST path="/api/dandisets/000008/versions/draft/publish/" host=api.dandiarchive.org request_id=108b9201-f5f1-431d-b35c-69b5d8ca0fc3 fwd="76.24.253.1" dyno=web.1 connect=2ms service=30002ms status=503 bytes=0 protocol=https
Feb 25 19:56:21 dandi-api app/web.1 [2021-02-26 03:56:21 +0000] [4] [CRITICAL] WORKER TIMEOUT (pid:14)
Feb 25 19:57:44 dandi-api heroku/router at=error code=H12 desc="Request timeout" method=POST path="/api/dandisets/000008/versions/draft/publish/" host=api.dandiarchive.org request_id=adbec448-751a-4c62-bd01-13e387a6a649 fwd="76.24.253.1" dyno=web.1 connect=1ms service=30001ms status=503 bytes=0 protocol=https
Feb 25 19:57:45 dandi-api app/web.1 [2021-02-26 03:57:44 +0000] [4] [CRITICAL] WORKER TIMEOUT (pid:20)
Feb 25 20:01:04 dandi-api heroku/router at=error code=H12 desc="Request timeout" method=POST path="/api/dandisets/000008/versions/draft/publish/" host=api.dandiarchive.org request_id=79d93274-101a-41b2-8d9d-62c2ed26d221 fwd="76.24.253.1" dyno=web.1 connect=1ms service=30000ms status=503 bytes=0 protocol=https
Feb 25 20:01:04 dandi-api app/web.1 [2021-02-26 04:01:04 +0000] [4] [CRITICAL] WORKER TIMEOUT (pid:17)
```
feel free to close if benign

**Comment by mgrauer** [comment]
We shouldn't post papertrail logs in github because that might expose some information that is better kept private. Also, just FYI, it would probably be more information rich for you to start with Sentry when we receive errors, and then use papertrail logging to support error investigation.

**Comment by yarikoptic** [comment]
do you mean that `request_id` is sensitive information? (I did eye ball for sensitive info).  Would it be ok to post tracebacks from sentry?
What I would like to have is a centralized registry (here) of issues as they occur - FTR and association of fixes (commits, PRs) with issues.  I am ok to not post any papertrail/sentry details but that would make it hard to associate/track down.

**Comment by mgrauer** [comment]
You can post a link to the sentry issue or a link to the papertrail view in a GH issue (and there may even be easier ways than that), then those of us with access can see all the details. Of course feel free to describe the problem here along with any relevant details about the conditions.

**Comment by yarikoptic** [comment]
roger that!  just to make it clear to myself -- is `request_id` sensitive?

**Comment by mgrauer** [comment]
There is nothing to clear yourself for! I'm just telling us to prevent problems for the future.

I don't think `request_id` is sensitive (not sure), but there are IPs in those logs and may be other sensitive details showing up, and even if you clean those details out, other people may not. So it is better to train ourselves not to post these here.

**Comment by yarikoptic** [comment]
@mgrauer @dchiquito feel welcome to close this issue if no longer appears in the logs upon publishing of 000008

**Comment by dchiquito** [comment]
I've put in some optimizations and publishing 000008 now takes ~1 second, so I'm going to close this.
