### ISSUE TITLE
workers should be able to run docker tasks

### ISSUE THREAD

**Issue by satra** [dandi/dandi-api#140]
@mgrauer - as part of running the worker on ec2 let's make sure the worker itself can run docker tasks. we will likely need that for certain types of validation. and then the validation job becomes something we can define outside of the api codebase potentially.

also let's consider whether aws batch would be useful in the current context for now. i personally like the idea of running an ec2 instance (easier to migrate), but if it's just a conceptual migration to say some other job queueing system perhaps AWS batch gives us all the benefits right now, without having to implement the queue ourselves.

**Comment by waxlamp** [comment]
I think this has been covered by the move of validation logic to dandischema, as well as the use of RabbitMQ and Celery via the Heroku deployments.
