### ISSUE TITLE
support multiple s3 endpoints

### ISSUE THREAD

**Issue by satra** [dandi/dandi-api#147]
We will likely end up with multiple buckets under dandi control.  in the backend for storing different access constraints. this may include backup integration to wasabi, support for gcs buckets., etc.,.

I wanted to put this in the wishlist, so we don't lose sight of this.

**Comment by waxlamp** [comment]
Is this still valid, @satra? We are now operating with two S3 buckets, and our infrastructure has absorbed that change in operating conditions.

**Comment by satra** [comment]
possibly. i would say this is similar to the issue that we may need to target different buckets for different needs. i don't think this has been generalized, but for the moment it would be low priority or orphaned.

**Comment by waxlamp** [comment]
I think my position is that it *has* been generalized, in the sense that when a new function is needed for which a new bucket needs to be in the system, we add that bucket through Terraform, and then identify that bucket in our code with environment variables, and make use of it through new logic, etc.

From the issue title, it sounds like you want a fully general mechanism for adding more buckets in an arbitrary fashion, but I don't think that would be possible for the use cases we have been working with. Let me know if I am missing something.

**Comment by satra** [comment]
i'll close this for now.
