### ISSUE TITLE
To end up with a Publish button soon after migration

### ISSUE THREAD

**Issue by satra** [dandi/dandi-api#154]
Things that need to happen to get to Publish and Publish workflow

- Schema release
   - Dandi schema to datacite schema
- Make sure draft/publish versions contain the same files (dandiset.yaml, assets.yaml)
- inject properties into published asset metadata without minting new uuids (perhaps this should already be done with existing assets)
- implement DOI minting functionality for dandisets
  - Decide how DOIs should be minted per version
- Citation UI with augmentation for citing specific versions of dandisets.

Publish workflow
- Has to be a valid dandiset
- Lock a dandiset for publishing (so no assets can be deleted)
- Make a new version
- Unlock dandiset
- Mint DOI and add to metadata
- Write out objects to S3

**Comment by dchiquito** [comment]
@satra I've added the basic functionality of DOI minting, dandiset.yaml and assets.yaml to the publish button. You can try it for yourself on https://gui-beta-dandiarchive-org.netlify.app/#/dandiset/000008/draft.

Can you check the results of a publish and provide some specifics as to how it needs to be improved? I believe all the raw materials are there, I just want to make sure that the output looks the way you want it to.

**Comment by satra** [comment]
@dchiquito - how do i check the results of publish? do i have access to the s3 bucket?

**Comment by dchiquito** [comment]
Yes, you would have to look in the S3 bucket to make sure `dandiset.yaml` and `assets.yaml` look correct. You would also have to use the DOI API or whatever console you might have access to to view the DOI.

**Comment by yarikoptic** [comment]
please share credentials/iam with access to that private bucket with me as well -- I would love to have a peak too.

**Comment by satra** [comment]
@dchiquito - just took a look at the info for dandiset 8 (just the latest published state). overall looks good for now. here are a few notes:

- contentUrl missing from asset metadata (this should be inserted even before publish for GET requests)
- for both dandisets and assets, it should include a couple of additional fields (publishedBy and datePublished). these are in the model currently, but i will take a look at the model more closely in the next day or two. 
- minted doi should be added to dandiset.yaml (i will determine the property/location)
- for aesthetic reasons, it would be nice to have `identifier, name, description` be the first 3 elements of dandiset.yaml and `path, contentUrl, contentSize` be the first 3 elements of each asset

**Comment by waxlamp** [comment]
This is done now.
