### ISSUE TITLE
Embargo support

### ISSUE THREAD

**Issue by yarikoptic** [dandi/dandi-api#158]
Later will be formalized as a design doc, but for now this issue could be a dump of ideas etc to formalize it from.  Various aspects will be in play. Here is what I see so far

- how much is embargoed: only data (blobs) or metadata as well. (I think: "only data (blobs)" would be a nice compromise with simpler solution while fostering discoverability and collaboration. @satra -- would that be in contradiction with anything NIH is thinking about?)
- (blob only if metadata public) storage space: completely separated from amazon-supported public bucket
- users: owners (full access) vs collaborators (read-only) - sending user requests to gain (read only or read write) access to embargoed datasets
- download: access rights 
- upload&de-duplication: no shortcut (based solely on "identity") for blobs which aren't already owned or "collaborated on"
- allow or not "publishing" (versions, without DOIs minting): I would say ideally versions should be allowed
- migration from embargoed to public space: trickier with versions in play see above
- embargo expiration: default to 1 year, allow for extended (till the grant end) if grant number is provided (and date automagically fetched)

Fancier wild features to consider:
- allow for drafts to be embargoed (private) but be publishable (publicly)

**Comment by yarikoptic** [comment]
Partial snapshot of discussion on slack in the wake of information from @satra 
![Screenshot_20210905-115715](https://user-images.githubusercontent.com/39889/132133335-915dc105-0999-417c-bbda-945da4a98b47.png)

**Comment by waxlamp** [comment]
I'm going to close this in favor of the in-flight embargo-related issues that are currently being worked on. All of the concepts listed here have been addressed in the design process. Thanks for kicking this off, Yarik!
