### ISSUE TITLE
should not add schema_version; should support/check for range of schemaVersions in metadata received

### ISSUE THREAD

**Issue by yarikoptic** [dandi/dandi-api#172]
I have freshly recreated 000004 on dandi-api instance, and queried its metadata but it provides old schema_version and new schemaVersion:
```
$> curl --silent -X GET "https://api.dandiarchive.org/api/dandisets/000004/versions/draft/" -H "accept: application/json" | jq . | grep -i version
  "version": "draft",
    "schemaVersion": "0.1.1",
    "schema_version": "1.0.0-rc1",
```

**Comment by waxlamp** [comment]
Grepping dandi-cli sources, I see:

```
dandi/models.py:    schemaVersion: str = Field(
dandi/models.py-        default=DANDI_SCHEMA_VERSION, readOnly=True, nskey="schema"
dandi/models.py-    )
```

and also:

```
dandi/tests/test_metadata.py:  "schemaVersion": "0.1.1",
dandi/tests/test_metadata.py:  "schemaVersion": "0.1.1",
dandi/tests/test_metadata.py:  "schemaVersion": "0.1.1",
```

Is `DANDI_SCHEMA_VERSION` set to the wrong value? Or maybe the hard-coded `"0.1.1"` in the tests are somehow involved?

**Comment by yarikoptic** [comment]
no -- dandi-cli tests nohow effect server or uploaded metadata.

hardcoded in the tests of dandi-cli just because they are tests but I think we should just use the constant (https://github.com/dandi/dandi-cli/issues/490) there as well.

the point here is probably that dandi-api injects additional field `schema_version` into metadata records, which is IMHO it should not do.

I think `dandi-api` should (I can later find where I had mentioned it before besides "metadata-versions" in #36)
- establish way to specify minimal/maximal supported version(s) of metadata.  Could be 
   -  V1: explicit "min_version_included" (e.g. `0.1.0`), "max_version_excluded" (e.g. `0.2.0` ATM) pair
   -  V2: logic that `0.1.0` means all until next `.MINOR`, and later starting from `1.0.0` that specifying e.g. `1.2.3` would be the minimal version all the way until (but not including) `2.0` .  In such a case it should be a list of supported "minimal" versions, e.g. `["0.5.3", "1.0.0"]` which would mean `["0.5.3", "2.0.0"]` in the V1 specification
- only check `schemaVersion` (not `schema_version`) for dandiset metadata records to confirm that it "understands" metadata of that `schemaVersion` for extraction/injection of the fields it cares about, and otherwise not alter the value of `schemaVersion`. 

I will retitle now this issue to be more reflective of this

**Comment by yarikoptic** [comment]
Also attn @satra to hear his thoughts regarding the "life of schemaVersion"

**Comment by dchiquito** [comment]
@yarikoptic I think that the `schema_version` was set to `0.1.0` in terraform last week, but that change was not deployed until I noticed it yesterday. I just opened 000004 in the metadata editor GUI and saved it again, and now it's reporting:
```
"schema_version": "0.1.0",
```
Does this resolve the issue?

**Comment by yarikoptic** [comment]
No. See new title and comment above https://github.com/dandi/dandi-api/issues/172#issuecomment-805941474

**Comment by yarikoptic** [comment]
With that in mind, I don't think schema version should be set at terraform level anyhow

**Comment by yarikoptic** [comment]
AHA -- silly me finally identified 1 use case on why `dandi-api` might needs to be aware of some specific version of the schema:  creation of a dandiset?  I have just created a new https://gui-beta-dandiarchive-org.netlify.app/#/dandiset/010000 using web UI, and I guess (can't check using swagger - forgot how to login) it was dandi-api (since found no relevant code in dandiarchive:django-api upon grepping for `schema_version`) which added `schema_version` field into dandiset metadata.  

So I guess besides the range of schemaVersions API supports it should  indeed "know" some specific version (ideally the most up-to-date) to populate `schemaVersion` (not `schema_version`) within metadata of a newly created dandiset.

**Comment by satra** [comment]
just like the CLI, it's the UI that should add the version when creating the new dandiset. i don't think API should add version, just check against version. so i think the original thought process still holds.

**Comment by yarikoptic** [comment]
agree with @satra -- since UI is the one to edit metadata anyways and should be aware of schemaVersion more "intimately" (e.g., meditor).  As a short fix (we need it since otherwise nobody can do create (on webui)/download/populate/upload cycle) dandi-api needs to just rename `schema_version` to `schemaVersion` and stop populating it anywhere but in `create`.
