### ISSUE TITLE
data ingress API(s):  upload, sync

### ISSUE THREAD

**Issue by yarikoptic** [dandi/dandi-api#176]
Urgency motivated by https://github.com/dandi/dandi-cli/issues/136 . 
It is time to discuss what mechanisms in our API we would provide for ingres of data into archive.  ATM `dandi-cli` just channels all the data through girder server even though it does not even use content-addressable IDs in the assetstore. (bottleneck and seems not robust for large files we are working with) 

Our perspective "ingress API" probably should allow to "redirect" to upload endpoints to S3 (so we wouldn't upload directly to the API server, but elsewhere).  If we do that, another generalization would be to provide `sync` operation (as @satra suggested yesterday) where API server would be able to "sync" from another location. For starters such location could be (the same) S3 bucket (e.g. in response to that "redirect" endpoint), but later we could possibly expand with additional (ipfs, globus, git-annex, ...) which would be relevant and feasible to support.

Here is my not very informed by other existing solutions (we are to check what other archives do!) possible workflow.
In the `info` record from API (https://github.com/dandi/dandi-publish/issues/80) we list `sync` mechanisms supported, e.g.
```yaml
# yaml representation of a possible portion of the likely json response
ingress:
 upload:
   mechanisms: ["redirect", "direct"]  # in order of preferance
 sync:
   mechanisms: ["s3", "globus", ...]`
```
then clients could go with a mechanism supported both by them (in their version) and specific server deployment, and we could "deprecate" older mechanisms without requiring users to update clients (if their installed client already supports needed mechanism).  Each mechanism would need its specific parametrization in the query/response. 

## "redirect"

Our prototypical "redirect" upload then would consist of 
- returning URL for PUT (with "authorization" token) to s3 or even more explicit record (`ingress: sync, mechanism: s3, bucket: dandiarchive, key: path, authkey: XXX, time-out: 3600`),   allowing for a file to be uploaded to key in our bucket
- client would upload file (e.g. robust multipart to s3) to it and issue `sync` request
- server would need to monitor that location, and in case of absent updates to it announced in timeout (within e.g. 3600 seconds per above), and remove that temporary upload location if still there but had not been updated within that period of time.

## "direct"

As for "direct" ingress.upload (in our specific deployment it is a bottleneck but would be more appropriate for some standalone dandiarchive deployment without any S3 bucket etc) we should provide support for robust upload (supporting retries on the same stream from a specific location or multipart upload so any part could be dropped if transmission fails). Again - to be researched, since I bet there are existing "standard" protocols/approaches/libraries, e.g. one of the first google hits is https://github.com/tus which seems has quite a wide range of implementations (JS, Python client)

**Comment by yarikoptic** [comment]
transferred to dandi-api from dandiarchive (web ui) since now it would be the most relevant venue where it should be implemented

**Comment by waxlamp** [comment]
Uploads now do go directly to S3, if I understand correctly. I believe that means this is no longer a concern.

**Comment by yarikoptic** [comment]
The issue was largely about supporting multiple methods of upload source (currently local drive), not as much destination (s3). But I guess we can create more specific one wherever first immediate use case comes about
