### ISSUE TITLE
publish: prevent publishing unless any change to the dataset

### ISSUE THREAD

**Issue by yarikoptic** [dandi/dandi-api#179]
Publishing "is not free": we will mint DOI, we possibly add other thousands of records for assets in the published version table.
ATM "publish" would happily publish a new version even if there is no changes to assets or dandiset metadata.
IMHO at some point we should introduce this "limiting" so that new version is not allowed to be published unless some difference from last version is found

**Comment by waxlamp** [comment]
I think this is done. @dchiquito, can you confirm?

**Comment by dchiquito** [comment]
This was resolved in #419
