### ISSUE TITLE
DOIs: ensure that they are Findable and not Draft

### ISSUE THREAD

**Issue by yarikoptic** [dandi/dandi-api#181]
On https://doi.test.datacite.org/repositories/dartlib.dandi/dois I see that all DOIs are marked as "Draft".  I have tried to switch a sample one to Findable  but encountered https://github.com/dandi/dandi-api/issues/180 and after switching type to Dataset and all persons to "Person" realized that form ui dropped all the names so could not save it.  But I think this might be a missing piece - that we need to announce DOIs not draft but "Findable" (IIRC the name correctly)

**Comment by yarikoptic** [comment]
I think all errors I saw in #180 are due to Findable requiring those extra fields/values.  I went for some earlier draft DOI https://doi.test.datacite.org/dois/10.80507%2F000001%2F0.210324.1512 which I manually updated.  So that one might be queriable now if anyone (@dchiquito @satra ) is eager to try

**Comment by waxlamp** [comment]
This is not actionable as written. @yarikoptic could you verify that this problem persists, and then clarify both the title and the description to aim us towards what to do?

**Comment by yarikoptic** [comment]
well, as for "actionable" it just needed a click on the link provided, login to the link provided to see if they are Draft or Findable. I did that and saw that most recent DOIs are
![image](https://user-images.githubusercontent.com/39889/125140841-6dd6f700-e0e1-11eb-9fbf-a87436f91e6c.png)

some other recent ones are still "Draft" ones though:
![image](https://user-images.githubusercontent.com/39889/125140911-96f78780-e0e1-11eb-84b8-2bdf7c6c72ee.png)

First findable is from March
![image](https://user-images.githubusercontent.com/39889/125140948-b1316580-e0e1-11eb-9ada-3bae7138ccc5.png)

So the question is: is that only one recent "draft" one recognized as some "failed attempt" which was detected/dealt with at dandi-api side as reporting an error or not bothering to try to mint it, or there is still a chance to get "Draft" DOIs if some metadata is missing or type of DOI is not specified? (I have not analyzed the situation leading to Draft vs Findable, hence issue had a question form since all DOIs were Draft... will rephrase now)

**Comment by yarikoptic** [comment]
probably unrelated but spotted that the Draft one has "Neural Data published 1970 via DANDI Archive" which sounds odd...

**Comment by dchiquito** [comment]
This was resolved in https://github.com/dandi/dandi-api/pull/451
