### ISSUE TITLE
Dockerized instance is running out of DB client connections

### ISSUE THREAD

**Issue by jwodder** [dandi/dandi-api#190]
Adding a mere four tests to the dandi-cli test suite causes the test suite to suddenly fail on the last two dandi-api tests out of 22 due to the dandi-api container encountering "psycopg2.OperationalError: FATAL: sorry, too many clients already".

Let me know what further details you need.

**Comment by jwodder** [comment]
I was able to get the tests to work again by making most dandi-api tests use the same `Session` instance, but I'm not convinced this problem won't rear its head again in the future.

**Comment by yarikoptic** [comment]
Smells to DBM ignorant me like some absent explicit session termination somewhere in dandi-api

**Comment by jwodder** [comment]
The problem came up again while I was adding more tests.

**Comment by jwodder** [comment]
Thanks to [this SO post](https://stackoverflow.com/a/66270520/744178), I was able to eliminate the error by passing `--nothreading` to the Django container's command.

**Comment by yarikoptic** [comment]
Note: the actual issue isn't resolved AFAIK, and there is a workaround of --nothreading added only to docker-compose of dandi-cli only https://github.com/dandi/dandi-cli/blob/0a2903f67bba8f4664fb488794c00c48b30586b9/dandi/tests/data/dandiarchive-docker/docker-compose.yml so anyone eventually trying to get their own instance running would get to the same situation IMHO
