### ISSUE TITLE
track implementation of out of band work pieces

### ISSUE THREAD

**Issue by satra** [dandi/dandi-api#191]
This issue is intended to add and to track out of band computations. Please edit this post with pointers to relevant issues as needed.

- [ ] checksum computations
- [ ] asset validation
- [ ] garbage collection

**Comment by waxlamp** [comment]
@satra: what's the purpose of maintaining this list as an issue? I'd prefer to keep issues actionable, and I'm not sure what the action here is.

**Comment by satra** [comment]
i think this was meant to be checked off when implemented. of this only the first two have been implemented. but whatever is being done out of band should also be documented somewhere.
