### ISSUE TITLE
checksum computation status

### ISSUE THREAD

**Issue by satra** [dandi/dandi-api#192]
@yarikoptic pointed me to a part of the upload process that launches an out of band sha256 compute job. does this job complete given the prior discussions about runtimes associated with celery workers? or has an external longer running worker already been implemented?

**Comment by yarikoptic** [comment]
FWIW, I do not see any other digest besides `dandi-etag` when querying metadata for a sample asset 
```
$> curl --silent -X GET "https://api.dandiarchive.org/api/dandisets/000003/versions/draft/assets/4b71dd17-dade-4ce0-889e-a3094cf2a21c/" -H "accept: application/json" | jq '.["digest"]'
[
  {
    "value": "1c41def924184940991785fc8725f256-175",
    "cryptoType": "dandi:dandi-etag"
  }
]
```
so if computed, not populated in metadata

**Comment by yarikoptic** [comment]
some were populated and some not, there is a dedicated issue for that: https://github.com/dandi/dandi-api/issues/254
