### ISSUE TITLE
Order fields in yaml files

### ISSUE THREAD

**Issue by dchiquito** [dandi/dandi-api#193]
For aesthetic reasons, it would be nice to have `identifier, name, description` be the first 3 elements of dandiset.yaml and `path, contentUrl, contentSize` be the first 3 elements of each asset.yaml

_Originally posted by @satra in https://github.com/dandi/dandi-api/issues/154#issuecomment-807263657_

**Comment by yarikoptic** [comment]
hm, I wonder if such aesthetics
- should be "encoded" in the schema (e.g. some optional `sort_order`  field which would then sort those with it first, and the other fields after alphabetically)
- should be for metadata UIs to provide in that order and keep metadata "tune up" away from the `dandi-api`?

**Comment by waxlamp** [comment]
> hm, I wonder if such aesthetics
> 
> [...]
> 
> * should be for metadata UIs to provide in that order and keep metadata "tune up" away from the `dandi-api`?

This would be my preference. It seems to be a lot of work to control the order of key emission during YAML serialization, and does not bring a lot of benefit. Better would be not to worry about YAML serialization, treat that as an incidentally human-readable bit of machine metadata, and let the clients make the metadata beautiful.
