### ISSUE TITLE
digest format change in asset GET

### ISSUE THREAD

**Issue by satra** [dandi/dandi-api#195]
the new schema 0.2.0 changes the digest format to be a dictionary. this affects the returned metadata of an asset. i believe this is being inserted on request, so should be a matter of reformatting.

```
  "digest": [
    {
      "value": "141118414bc61a63ee298fcc1f103a35-126",
      "cryptoType": "dandi:dandi-etag"
    }
  ],
```
should become
```
  "digest": 
    {
      "dandi:dandi-etag": "141118414bc61a63ee298fcc1f103a35-126"
    },
...
```

**Comment by waxlamp** [comment]
Done.
