### ISSUE TITLE
mismatch between draft and publish dataset

### ISSUE THREAD

**Issue by satra** [dandi/dandi-api#199]
https://gui-beta-dandiarchive-org.netlify.app/#/dandiset/000003/0.210331.2159 has much smaller size and number of files compared to the draft dataset https://gui-beta-dandiarchive-org.netlify.app/#/dandiset/000003/draft

@yarikoptic - did you hit publish while uploading? i don't think i have fancy privileges so can't hit publish to see if a new dataset would reflect the full size.

**Comment by yarikoptic** [comment]
Hm... I thought I did press publish after it finished uploading. Website says March 31, 2021 at 05:59 PM for published and earlier time for draft, and I would assume that time changes if any asset is updated (we would need to add a test for that). Did you compare a list of assets for draft and published?

**Comment by yarikoptic** [comment]
So most likely some publish bug. I wonder if it managed to skip assets which didn't get have saying off band (sha256?) jobs completed?

**Comment by yarikoptic** [comment]
Or just that job took longer than 30 sec and was killed, like in the case of providing upload urls? I didn't eye ball the logs - just throwing wild ideas

**Comment by dchiquito** [comment]
It was published while still uploading. I published it again (several times) and those versions match the draft.
The first version has only 14 assets in it, while the second version has 101. The first 14 assets in the second version are the same as the assets in the first version. Here are some creation dates:
```
Asset #14
2021-03-31T21:57:58.660770+00:00
Version #1 (publishing == creating a new version)
2021-03-31T21:59:35.571747+00:00
Asset #15:
2021-03-31T21:59:39.704713+00:00
```
Version 1 was published while there were only 14 assets.

Tragically the dates in the UI represent the time the `Version` row in the DB was last modified, which does not update when assets are added/removed, as they are not in the row. That should be fixed.

**Comment by satra** [comment]
thanks @dchiquito - i'll close this for now.
