### ISSUE TITLE
enable publish only when dandiset is valid

### ISSUE THREAD

**Issue by satra** [dandi/dandi-api#202]
this is not a migration blocker (`*`), but the kind of thing that the server has to encode. at the very least there should be a validated flag that turns on or off when assets or metadata are changed for a given dandiset. and also a validated flag on an asset. we should discuss what the processes are required for validation to actually pass.

`*` we should do the blocking of publish (unless it is only an admin privilege at this point) right before migration actually happens, so that people do not hit publish right away. perhaps this is currently prevented by admin privileges, since i couldn't click on the publish button.

**Comment by waxlamp** [comment]
Done.
