### ISSUE TITLE
modify metadata return for dandiset GET

### ISSUE THREAD

**Issue by satra** [dandi/dandi-api#206]
while the asset GET returns metadata only the dandiset GET embeds metadata. we should make this uniform.  this should inject a few things into the returned metadata record (e.g., url, version).

**Comment by waxlamp** [comment]
@satra: can you clarify what you mean by "returns" vs "embeds"?

**Comment by satra** [comment]
this is now resolved. for example, https://api.dandiarchive.org/api/dandisets/000004/versions/draft/ returns only metadata
