### ISSUE TITLE
DJANGO_API: Publish of a dandiset during upload silently does nothing

### ISSUE THREAD

**Issue by yarikoptic** [dandi/dandi-api#208]
I am still uploading https://gui-beta-dandiarchive-org.netlify.app/#/dandiset/000020 which is large in numer of files.  To check if I can publish while it is being uploaded (as it was suggested on what has happened in https://github.com/dandi/dandi-api/issues/199#issuecomment-811929491) -- I pressed Publish when it was at about 1900 files uploaded.  Nothing happened. Pressed again a few times - nothing happened.  In papertrail I saw some errors on that but since advised not to copy paste into public, I don't .  It happened around now (`Thu 01 Apr 2021 05:59:10 PM EDT`)

trying in swagger (curl analog was `curl -X POST "https://api.dandiarchive.org/api/dandisets/000020/versions/0.000000.0001/publish/" -H  "accept: application/json"`) lead to 

```
Code | Details
-- | --
404Undocumented | Error: Not FoundResponse bodyDownload{   "detail": "Not found." }
```

**Comment by yarikoptic** [comment]
and it might have nothing to do with "during upload" since now dataset is fully uploaded and `Publish` still doesn't work

**Comment by dchiquito** [comment]
Some server logs:
```
Apr 05 06:07:02 dandi-api app/web.1 [13:07:02] ERROR    Failed to create DOI 10.80507/000020/0.210405.1307 doi.py:77
Apr 05 06:07:02 dandi-api app/web.1            ERROR    {'data': {'id': '10.80507/000020/0.210405.1307',   doi.py:78
Apr 05 06:07:02 dandi-api app/web.1                     'type': 'dois', 'attributes': {'event': 'publish',          
Apr 05 06:07:02 dandi-api app/web.1                     'doi': '10.80507/000020/0.210405.1307',                     
Apr 05 06:07:02 dandi-api app/web.1                     'creators': [], 'titles': [{'title':                        
Apr 05 06:07:02 dandi-api app/web.1                     '20200611_AIBS_mouse'}], 'publisher': 'DANDI                
Apr 05 06:07:02 dandi-api app/web.1                     Archive', 'publicationYear': 2021, 'contributors':          
Apr 05 06:07:02 dandi-api app/web.1                     [], 'types': {'resourceTypeGeneral': 'Dataset'},            
Apr 05 06:07:02 dandi-api app/web.1                     'url': 'https://dandiarchive.org/dandiset/000020/0          
Apr 05 06:07:02 dandi-api app/web.1                     .210405.1307'}}} 
```
I believe this is because `creators` is `[]`. This is a simple case of invalid metadata being passed to Datacite.

This issue should be resolved by the forthcoming design doc, so I'm closing it.
