### ISSUE TITLE
DOI: switch to "production" datacite instance

### ISSUE THREAD

**Issue by yarikoptic** [dandi/dandi-api#213]
ATM we are using sandbox of datacite.

Other issues for `publish` milestone: https://github.com/dandi/dandi-api/issues?q=is%3Aopen+is%3Aissue+milestone%3A%22feature%3A+publish%22

If  we would like to have DOI minting as part of Publish, to "release" "Publish" functionality we would need to switch to production (not sandbox).  For that (in addition to current publish issues), we would need to

- [ ] decide on DOI schema.  ATM it is `<DANDISET>/<VERSION>` - neat as such, `/` in it might be problematic although allowed (TODO: need to find the issue/PR where it was discussed)
- [ ] ensure that we do not start excessively mint DOIs: we should not allow for DOI to be minted if #179

**Comment by waxlamp** [comment]
@dchiquito, can you give an update on the status of this issue?

**Comment by waxlamp** [comment]
@dchiquito ^^^

**Comment by dchiquito** [comment]
This was fixed back in https://github.com/dandi/dandi-infrastructure/commit/c5e18cbcff3210990f43bec762f7759a1f598be8
