### ISSUE TITLE
page size greater than 100 has not effect on GET on assets

### ISSUE THREAD

**Issue by satra** [dandi/dandi-api#252]
both the following snippets return 100 records. if number is less than 100, it returns the appropriate number.

```python
import requests
url = "https://api.dandiarchive.org/api/dandisets/000026/versions/draft/assets/"
querystring = {"path":"sub-I46/microscopy","page_size":"100"}
headers = {"Accept": "application/json"}
response = requests.request("GET", url, headers=headers, params=querystring)
len(response.json()["results"])
```

```python
querystring = {"path":"sub-I46/microscopy","page_size":"1000"}
response = requests.request("GET", url, headers=headers, params=querystring)
len(response.json()["results"])
```

**Comment by yarikoptic** [comment]
confirming that it remains the case!

**Comment by waxlamp** [comment]
There is a `max_page_size` value of `100` set on the API pagination scheme. I've increased it to 1000 in #317, but this might be too high. In any case I think it's important to keep a hard-coded limit like this to mitigate accidental DoSing.
