### ISSUE TITLE
add "metadata=False|True" option to /dandisets/.../assets/ end point

### ISSUE THREAD

**Issue by yarikoptic** [dandi/dandi-api#255]
ATM we need to issue a separate query for each asset separately, makes many operations slow and places more burden on API server.  I think the easy way to mediate it is to make dandi-api allow for returning listing with metadata if so desired.

**Comment by satra** [comment]
i would suggest we make the returns consistent for dandisets, dandisets/versions and assets. i would like to see a consistent return structure that is either the entire metadata or a subset of the fields for efficiency. anything paginated can have `"count", "next", "results"` as the top level structure.

**Comment by yarikoptic** [comment]
+1 on that .  Indeed we should be consistent in our listings of dandisets or assets.  I would say by default to return listing of records without metadata unless it is requested explicitly.  We should check our elderly API design notes -- I think we had that "in mind" ;)

**Comment by yarikoptic** [comment]
I think this might be a duplicate of  #100

**Comment by yarikoptic** [comment]
ok, let's consider this and #100 superseded by a more generic https://github.com/dandi/dandi-api/issues/397
