### ISSUE TITLE
API has a cross-origin policy that does not allow other browser clients

### ISSUE THREAD

**Issue by satra** [dandi/dandi-api#256]
mostly an fyi for now, but we should provide a way for accessing the API from other browser clients.

>Access to fetch at 'https://api.dandiarchive.org/api/dandisets/000043/versions/draft/' from origin 'https://cdpn.io' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource. If an opaque response serves your needs, set the request's mode to 'no-cors' to fetch the resource with CORS disabled.

**Comment by waxlamp** [comment]
The way to do it now is for us to whitelist domains that are allowed to access the API via browser. This is somewhat akin to other scenarios where you have to apply to gain access to something (e.g., maps API, etc.).

If you think this is sufficient, I can close this issue and open a specific issue to allow CodePen to access the API. Let me know how you'd like to proceed.

**Comment by satra** [comment]
perhaps we can start with codepen for now. but in general we do want to consider why a client side app on gh-pages (so potentially custom domain) should not be allowed to talk to the API without requesting CORS support. i.e. what the security implications are that we are worried about.

**Comment by waxlamp** [comment]
I believe the risks are general. For instance, allowing any website to make requests to the DANDI API server opens up avenues of attack via CSRF/XSS. I also believe such attacks can be defended against but we need to do so deliberately.

I am not an expert in the security aspects here. @brianhelba can likely give much better information.

**Comment by brianhelba** [comment]
I'd suggest conducting a review of all endpoints with an eye towards how they could be abused via CSRF. If any vulnerabilities are found which can't be remedied, those particular endpoints can be blocked from CORS access.

At that point, I think it could be safe to switch to a CORS Origin policy of `*`.

For new (or significantly changed) endpoints in the future, the same analysis should be conducted.

---
Beyond CORS, also note that in order to authenticate via OAuth2, third party web clients will still need to register and obtain an application ID.

**Comment by waxlamp** [comment]
@satra, I've added codepen.io to the whitelist. Can you check whether it's working as intended?

**Comment by dchiquito** [comment]
We have already set up an allowed origin (gui.dandiarchive.org), so we would need the Origin `gui.dandiarchive.org` to have access to all Methods (including PUT/POST), while everyone else (`Origin: *`) would only have access to read only Methods (`GET`, `HEAD`, `OPTIONS`). I don't see a way in [django-cors-headers](https://github.com/adamchainz/django-cors-headers) to have tiers of CORS allowed-ness, so I don't see a way to only permit the harmless requests.

Simply turning off CORS altogether is an option, but we should think more carefully about our threat model first.

**Comment by waxlamp** [comment]
> We have already set up an allowed origin (gui.dandiarchive.org), so we would need the Origin `gui.dandiarchive.org` to have access to all Methods (including PUT/POST), while everyone else (`Origin: *`) would only have access to read only Methods (`GET`, `HEAD`, `OPTIONS`). I don't see a way in [django-cors-headers](https://github.com/adamchainz/django-cors-headers) to have tiers of CORS allowed-ness, so I don't see a way to only permit the harmless requests.

Can we use the [signals](https://github.com/adamchainz/django-cors-headers#signals) feature to implement this sort of discrimination? Basically, examine the `request` for its origin and method, and respond appropriately?

**Comment by satra** [comment]
perhaps there is something similar to how we do this in nginx: https://enable-cors.org/server_nginx.html

**Comment by waxlamp** [comment]
> perhaps there is something similar to how we do this in nginx: https://enable-cors.org/server_nginx.html

The policy in that Nginx example is readily implementable in Django without any trouble. What we want is to respond differently based upon the origin making the request, and the methods they wish to use. I think the signals mechanism I linked to above will allow us to do that, but I'd like @dchiquito's take on that.

**Comment by dchiquito** [comment]
I skimmed right over that bit of the docs. It does look like signals offer exactly what we want:
> A common use case for the signal is to allow all origins to access a subset of URL's, whilst allowing a normal set of origins to access all URL's. This isn't possible using just the normal configuration, but it can be achieved with a signal handler.

This is almost exactly our use case, except we need to filter on methods, not URLs.

**Comment by waxlamp** [comment]
> I skimmed right over that bit of the docs. It does look like signals offer exactly what we want:
> 
> > A common use case for the signal is to allow all origins to access a subset of URL's, whilst allowing a normal set of origins to access all URL's. This isn't possible using just the normal configuration, but it can be achieved with a signal handler.
> 
> This is almost exactly our use case, except we need to filter on methods, not URLs.

As long as the `request` object informs about the method (which I can't imagine it doesn't), then I think we should try this method.

@dchiquito, can you take a run at it?
