### ISSUE TITLE
Add a less scary "From" field in emails from the service

### ISSUE THREAD

**Issue by yarikoptic** [dandi/dandi-api#258]
Added dandibot to a dandiset owners, and then received (nice!) an email announcing that with a scary

```
From: admin@developmental-leek-si57sxgm3k1xthxawtj3h6zr.herokudns.com
```

I think ideally it should be something like

```
From: DANDI Archive <noreply@dandiarchive.org>
```
or alike and not leak deployment specifics in it.

**Comment by waxlamp** [comment]
@brianhelba, is this something we can control via SES settings in dandi-infrastructure?

**Comment by satra** [comment]
this may also be related to the requested email addresses which went missing after the transition to amazon DNS + SES.
- info@dandiarchive.org
- help@dandiarchive.org

obviously noreply doesn't need to exist :)

**Comment by waxlamp** [comment]
This has been solved. It turns out its only the people subscribed to the mit.edu mailing list that see these scary From fields; ordinary users are seeing the correct email headers.

**Comment by yarikoptic** [comment]
so it was only partially solved.

**Comment by waxlamp** [comment]
I considered it a problem that ordinary users might be seeing "scary" headers. If the mit.edu email servers are rewriting headers and causing ugly emails for just the admin team, that seems to be out of scope for the DANDI project to fix.

There are nonetheless other fixes available, like moving our email list to google or some other provider, or even asking MIT admins what's going on. But as far as this GitHub issue is concerned I consider the problem solved.
