### ISSUE TITLE
add citation and a few other computed fields to returned dandiset metadata

### ISSUE THREAD

**Issue by satra** [dandi/dandi-api#262]
this is a quick pass. (also addresses: https://github.com/dandi/dandiarchive/issues/645)

to add to dandiset metadata:
- version (currently missing)
- id = f"{identifier}/{version}"
- url =  f"https://identifiers.org/{id}"
- citation (see funcs below)

here is a simple piece of code. if we add this to api and add the citation field to the returned metadata. that would be the easiest thing to start with. and if we add "id" addition to the API which is identifier + version

we may want to store the gif in the assets of the web ui.

```python
from datetime import datetime

def orcid(contrib, publish=False):
    if "identifier" in contrib and contrib["identifier"] and not publish:
        return f'<a href="https://orcid.org/{contrib["identifier"]}"><img src="https://info.orcid.org/wp-content/uploads/2020/12/orcid_16x16.gif" /></a>'
    return ''

def citation(metadata):
    cl = "; ".join([val["name"]+orcid(val) for val in metadata["contributor"] if val["includeInCitation"]])
    YEAR = datetime.now().year
    citestr = f"{cl} ({YEAR}) {metadata['name']}. Online: {metadata['url']}"
    return citestr
```

**Comment by yarikoptic** [comment]
ok, enough for me for today. Reading 

> we may want to store the gif in the assets of the web ui.

made me think of you suggesting to store citation as a gif as some kind of a dandi asset ;)  yeah -- we should provide a copy of the orcid little icon.  I thought to suggest "let's do svg" and interestingly https://info.orcid.org/brand-guidelines/ says "Use the scalable SVG icon wherever possible." but provides html example with a png, and actually use .gif in their html on the page. heh heh

**Comment by satra** [comment]
@dchiquito - while you tweak this i would also add: #231 (i.e. the second returned contentUrl should not be a signed one and only contain the path to a blob store location. since this is returned with the metadata, content disposition is not necessary.

```
[
  "https://api.dandiarchive.org/api/dandisets/000003/versions/draft/assets/8d21b488-9663-4816-8ff5-decc45591353/download/",
  "https://dandiarchive.s3.amazonaws.com/blobs/2b3/12a/2b312a36-2c3d-4467-a658-6f352a6cdb6e"
]
```

**Comment by satra** [comment]
another thing. when you add this, please completely ignore the orcid html component. that's the kind of thing that should be done on the UI side based on the contributor info.
