### ISSUE TITLE
provide blob_id within asset record?

### ISSUE THREAD

**Issue by yarikoptic** [dandi/dandi-api#264]
replying to @bendichter I realized that we do not anyhow return a blob_id associated with the asset whenever listing assets.  metadata should not have it I guess because it is dandi archive specific id.  But shouldn't we return it along side with `path` etc?

I am thinking -- probably not ;) because "what for"?  if someone needs access to the content, they have contentUrls to go by.  If we expose it  for the purpose of finding the blob in S3 -- user would need to construct full path in blob store, which is IMHO should not be encouraged etc.

Decided to file this "question" regardless.  @satra WDYT?

**Comment by bendichter** [comment]
What do you mean by contentUrls. I am trying to create a platform that can explore files in a dandiset and stream from them.

**Comment by waxlamp** [comment]
@yarikoptic or @bendichter, could you provide some context for this? I am not sure what the question or problem is.

**Comment by satra** [comment]
> I am thinking -- probably not

i agree :)
