### ISSUE TITLE
github ids needed for dandihub

### ISSUE THREAD

**Issue by satra** [dandi/dandi-api#268]
in girder, the github ids were stored in user profiles. in the new api github id's are not stored. we need these for enabling the users to access dandihub.

**Comment by waxlamp** [comment]
Stored in user profiles, meaning the API would tell you a user's GitHub ID?

More generally, what has to change in order to restore linking to dandihub?

**Comment by waxlamp** [comment]
> i didn't see the id stored in user profiles. i.e. i would have to use the API key to retrieve it.

I should have been clearer in my previous question: I am not sure what a "user profile" is in context. I was trying to ask if you meant that the user information endpoint should contain this information, or if you meant something else by "user profile".

> 
> in the ideal world, we should enable SSO. if you login to api server, you should be able to log in to hub.dandiarchive.org. but we will likely want to control different levels of resource access, so a pure SSO doesn't work. but the first place to start would be SSO.

If there's a way to restore what we used to do with Girder3, I'd like to solve this issue by doing that. If we want to have SSO between dandiarchive and dandihub, that seems like a much heavier solution that should be filed in its own issue (and will require some discussion, design docs, etc.).

**Comment by satra** [comment]
to do basic restore without SSO, i need a returned set of github id's when i query users (admin privilege is fine).

**Comment by dchiquito** [comment]
If you need their github handle, you can click on an email and look for the `login` field in the `Extra data` texfield: https://api.dandiarchive.org/admin/socialaccount/socialaccount/5/change/

**Comment by dchiquito** [comment]
I poked through the DB and sent you a list. Let me know if you need more than that.

**Comment by waxlamp** [comment]
The new user email indicates the GitHub ID, so I assume that is sufficient to close this issue. If we want to have programmatic access to DANDI users' GitHub accounts, let's file a new issue to figure that out.
