### ISSUE TITLE
Analyze and optimize logs archival

### ISSUE THREAD

**Issue by yarikoptic** [dandi/dandi-api#269]
Papertrail email says
```
Your Papertrail service for "dandi-api" has reached 91% of its included log data transfer of 250 MB for today.

This is an informational notice. No action is needed.

Based on recent volume, your projected total daily log data transfer is 265.8 MB.

How's this work?

At capacity, new logs are dropped.
```
so it seems we can loose some logs. There are options for filtering etc. We should look into adjusting configuration to ensure that we do have relevant logs preserved and any irrelevant filtered out

**Comment by waxlamp** [comment]
I was just looking at this. Do you know why we had such a spike in activity on Friday and Saturday?
