### ISSUE TITLE
docker-compose: make redirector for dandi paths work

### ISSUE THREAD

**Issue by yarikoptic** [dandi/dandi-api#273]
in a local instance instantiated via docker-compose, I do have a dandiset registered (in drafts) but URLs such as https://localhost:8092/dandiset/000000/draft do not work.

**Comment by waxlamp** [comment]
Going to close this because I don't believe making the redirector work in a local dev setup is necessary.

**Comment by yarikoptic** [comment]
Eventually we should come back to this, but probably not in the scope of individual component (dandi-API)
