### ISSUE TITLE
API call which would return information on supported features

### ISSUE THREAD

**Issue by yarikoptic** [dandi/dandi-api#274]
First need is to report to the dandi cli which minimal version of the client is good (and may be also black list some). That would include uploads by older clients which might not be eg uploading metadata in the desired format etc

We could also announce minimal version of nwb etc

**Comment by waxlamp** [comment]
This seems like an issue for the CLI to solve. We do need to figure out how to report the API version but once that is in place, the CLI should abort its own operation if the version number from the API is incorrect.
