### ISSUE TITLE
endpoint for dataset level stats

### ISSUE THREAD

**Issue by satra** [dandi/dandi-api#276]
could we add an endpoint that provides dataset level stats

`POST /dandi/{identifier}/stats`

this should return at least the pieces we would need for publishing and should be updated/extracted based on changes to the dataset.

these are the aggregate pieces we will need for publishing: 

  - "@id": schema:contentSize
    schema:domainIncludes: dandi:Dandiset
  - "@id": dandi:numberSubjects
    schema:domainIncludes: dandi:Dandiset
  - "@id": dandi:numberSamples
    schema:domainIncludes: dandi:Dandiset
  - "@id": dandi:numberCells
    schema:domainIncludes: dandi:Dandiset
  - "@id": dandi:dataStandard
    schema:domainIncludes: dandi:Dandiset

  - "@id": dandi:modality
    schema:domainIncludes: dandi:Dandiset
  - "@id": schema:measurementTechnigue
    schema:domainIncludes: dandi:Dandiset
  - "@id": schema:variableMeasured
    schema:domainIncludes: dandi:Dandiset

please also see the PR to dandi-core where the discussion/development of the final form of the schemas is happening.

**Comment by waxlamp** [comment]
Would like an update on this: @satra, is this still a concern, or is it subsumed by the work on asset summary generation?

**Comment by satra** [comment]
this is subsumed by the assets summary.
