### ISSUE TITLE
Download minio data in celery container

### ISSUE THREAD

**Issue by dchiquit** [dandi/dandi-api#29]
When the celery service needs to communicate with other services (specifically minio), it needs to address them directly by service name like http://minio:9000/whatever instead of http://localhost:9000/whatever. When generating the URL to download the data for validation, it looks something like http://localhost:9000/dandi-dandisets/test.txt?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=minioAccessKey%2F20201202%2Fus-east-1%2Fs3%2Faws4_request&X-Amz-Date=20201202T223646Z&X-Amz-Expires=604800&X-Amz-SignedHeaders=host&X-Amz-Signature=6ba8022bd45a5e9242c71adc891f3f724a4ac4ac1f83ed7b2f221f00d9ced7ec. This is arguably correct, because this link works correctly from outside the containers. When the celery service tries to use that URL however, it does not know to associate localhost with the minio service, so it just fails.

First referenced in https://github.com/dandi/dandi-cli/issues/277#issuecomment-737543809

**Comment by jwodder** [comment]
@dchiquit Is there an ETA on this fix?

**Comment by dchiquit** [comment]
I do not have an ETA.
If celery could somehow determine if it was running in a container, it could switch out `localhost` for `minio` before trying to use the URL. I don't know how to check that though.
@brianhelba Any thoughts on a solution?

**Comment by jwodder** [comment]
@dchiquit How about defining an environment variable (say, `MINIO_LOCAL_NETWORK_HOST=minio`) in `docker-compose.yml` that Celery checks for and uses to rewrite minio URLs?

**Comment by brianhelba** [comment]
@dchiquit The behavior you describe is intentional and is caused by the `DJANGO_MINIO_STORAGE_MEDIA_URL` environment variable.

In the context of a Celery worker, files should not be downloaded via URL, but should be loaded directly via a `FieldFile` on a model instance (or via Storage if absolutely necessary). Is there a reason that files are being fetched via URLs instead?

**Comment by dchiquit** [comment]
I believe you are correct, I just neglected to download it correctly. I will try to get a fix in today.

**Comment by dchiquit** [comment]
@jwodder I've tested the docker-compose locally and it should be fixed. Please reopen if docker-compose still doesn't work for you.
