### ISSUE TITLE
Do not allow multiple publishes

### ISSUE THREAD

**Issue by dchiquito** [dandi/dandi-api#290]
Right now you can click publish multiple times without changing the draft. This shouldn't be allowed.

**Comment by waxlamp** [comment]
Is there a dandiarchive portion to this issue as well? (i.e., gray out the publish button if publishing will fail for reasons of no pending edits, etc.?)

**Comment by dchiquito** [comment]
Plan is to add a new version validation state `PUBLISHED` that metadata takes on after publish happens.

**Comment by waxlamp** [comment]
I believe #419 closes this issue--correct, @dchiquito and/or @mvandenburgh?
