### ISSUE TITLE
make sure that we can handle large uploads

### ISSUE THREAD

**Issue by yarikoptic** [dandi/dandi-api#30]
echoing https://github.com/dandi/dandiarchive/issues/517 and a find on https://uppy.io/docs/aws-s3-multipart/#:~:text=S3%20requires%20a%20minimum%20chunk,10%2C000%20chunks%20per%20multipart%20upload that 

S3 requires a minimum chunk size of 5MB, and supports at most 10,000 chunks per multipart upload. If getChunkSize() returns a size that’s too small, Uppy will increase it to S3’s minimum requirements.

numbers in our issue suggest that we hit a cut off at 1,000 chunks though... it is all analytics and not proven, but something to keep in mind while implementing multi-chunked upload.  We might need to resort to scaling single chunks (if not done yet) based on the file size

Identified (and possibly fixed if "checked") blockers:
- [x] #184  - upload urls might expire before client is "done"

**Comment by satra** [comment]
some more details here: https://docs.aws.amazon.com/AmazonS3/latest/dev/qfacts.html

apparently the last part can be any size but the max size per part is still 5G, which would limit to max 1000 parts given max object size is 5T. however 5*10000 = 50T - so i'm missing some additional limit info here.

**Comment by satra** [comment]
this is done up to 5T. if we get to bigger files, will file newer issue.

**Comment by yarikoptic** [comment]
yes, but https://github.com/dandi/dandi-api/issues/185 might still forbid upload of 5TB files on a busy day due to exceeding 30 sec job limit to mint the upload urls
