### ISSUE TITLE
url added to dandiset metadata is incorrect

### ISSUE THREAD

**Issue by satra** [dandi/dandi-api#305]
at least in this dandiset, the url added looks like this:

`  "url": "https://dandiarchive.org/000004/draft",`

should be:

`  "url": "https://dandiarchive.org/dandiset/000004/draft",`

i'm posting this to just track it. i should have a cleaned up dandischema to detect all of these issues. and the changes could be incorporated in one go, including using the schema for validating both assets and dandisets.

**Comment by waxlamp** [comment]
I'm assuming this has been resolved.

**Comment by yarikoptic** [comment]
In assumptions we trust...

```shell
$> curl --silent -X GET "https://api.dandiarchive.org/api/dandisets/000004/versions/draft/" -H "accept: application/json" | jq . | grep url
  "url": "https://dandiarchive.org/dandiset/000004/draft",
        "identifier": "http://purl.obolibrary.org/obo/NCBITaxon_9606"
      "url": "https://osf.io/hv7ja/",
      "url": "https://www.nature.com/articles/s41597-020-0415-9",
```
so seems indeed be fixed if that is the endpoint @satra was talking about (detail wasn't provided)
