### ISSUE TITLE
In defense of the immuatable metadata records

### ISSUE THREAD

**Issue by yarikoptic** [dandi/dandi-api#311]
In light of recent discussions, I decided to centralize by notes since I had noted on a number of use cases but there is no central collection of them.

Overall I do think it is "feasible" to mutate metadata, but in some cases it would introduce data **duplication** (e.g. for size/digests etc) and special provisioning might need to be done to guarantee consistency. In some other cases: it would complicate metadata editing **logistics** wherever some activity (e.g. dandiset's `assetsSummary`) would store directly and ONLY in the metadata record.

## Asset metadata

- populated fields (we have BareAsset, so these are the only ones for `Asset`): `id`, `identifier`, `contentUrl`

### Use cases

- AUC1:
  - type: logistics
  - scenario: metadata is edited (no change to blob etc). New `identifier` so `contentUrl` should be reset/populated

## Dandiset metadata

- populated fields: `citation`, `assetSummary`, `manifestLocation`

### Use cases

- DUC1:
  - inspired by: review of https://github.com/dandi/dandischema/pull/6/files#diff-43c9cc813638d87fd33e527a7baccb2fd7dff85595a7e686bfaf61f0409bd403R878
  - type: logistics
  - scenario: user editing metadata in meditor while assetSummary is being updated
    - saving updated metaData record should not just save updated metadata record in full.  It should probably then use read-only elements straight from the record in the metadata record it has in DB so `assetSummary` is not overridden with a stale one

**Comment by waxlamp** [comment]
Closing this as FOI
