### ISSUE TITLE
remove code/text duplication in email send out

### ISSUE THREAD

**Issue by yarikoptic** [dandi/dandi-api#314]
a minor ATM but I guess should become more pertinent if we are to send various announcements.

ATM code/text duplicated in dandiapi/api/mail.py to provide html and text "renditions" of the same email.

**Comment by waxlamp** [comment]
Is there a strong reason to want to send both text and html formats? Just restricting to text would be less code, less maintenance, and perfectly user friendly.

**Comment by yarikoptic** [comment]
I don't know of any strong reason besides convenience in that we could go rogue and inject some malicious urls into HTML version so our recipients do not even see them ;)  I expect any modern mail client/setup to auto-detect urls in the text version and make them clickable (while giving 100% match of what-you-see-is-where-you-go)
