### ISSUE TITLE
/users (dandisets_users_read): provide more detailed record?

### ISSUE THREAD

**Issue by yarikoptic** [dandi/dandi-api#319]
In the spirit of `/files` about to get more information returned (#312 ), I think /users for a dandiset should return full public record not just  username + name.  ATM it seems to be only one extra field: `admin` so it should really have no notable performance penalty ;-) but even if extended, I think it would be just fine to return full records.

While at it, might be worth RF API to make `​/users​/` more consistent with the rest of the API, by allowing for `/users/{username}` to get an exact record.  ATM it is needed to use `/users/search​/` and then filter result to match username exactly (now e.g. `yarikoptic` would return 2 since I am a crowd ;)). (`{username}` is guaranteed to be unique, right?)

originally thought of by @jwodder while working on dandi-cli Python API redesign: https://github.com/dandi/dandi-cli/pull/447/files#diff-ca726fb8fbfbf61284ae89742c7c5621e5d4305fc9fd8a83047f71eb07a28379R118

**Comment by waxlamp** [comment]
I don't think we should expose `admin` status in the public API, unless there's some specific need to do so. I am also against changing the endpoint just for consistency--I would prefer to have a positive reason for doing the work.

I am not seeing the connection between the linked doc and this issue; could you explain?

Going to close this unless/until there's a compelling reason to do this work.
