### ISSUE TITLE
api server landing page

### ISSUE THREAD

**Issue by yarikoptic** [dandi/dandi-api#320]
continuation to #119  (and may be some other recently closed issue I failed to find ATM)

ATM both https://api.dandiarchive.org/ and https://api.dandiarchive.org/api/ stimply 404. IMHO it is suboptimal. I would have at least populated them with some basic information about API server (URL to swagger, may be this repository) or at least redirected somewhere (https://api.dandiarchive.org/swagger/ might not be the worst choice).

**Comment by waxlamp** [comment]
I am against a redirect, but I think it would be reasonable to put a static page at the root that contains links to other interesting resources (admin page, API root, Swagger docs, DANDI archive website, GitHub repo).
