### ISSUE TITLE
cannot change ownership of a dandiset on staging even as admin

### ISSUE THREAD

**Issue by satra** [dandi/dandi-api#334]
i suspect this is coming from a weird API request.

to reproduce: click on dandiset (i tried as admin), click on manage, and add new user as owner.

![image](https://user-images.githubusercontent.com/184063/122063714-8263f000-cdbe-11eb-9eaf-7b607ec19d38.png)

![image](https://user-images.githubusercontent.com/184063/122063480-4df03400-cdbe-11eb-9421-ca938a0215be.png)

**Comment by dchiquito** [comment]
After merging `master` into `staging` this problem seems resolved to me. Please reopen if it appears again.
