### ISSUE TITLE
Fix problem with deep file hierarchies

### ISSUE THREAD

**Issue by waxlamp** [dandi/dandi-api#360]
There's some problem in the API with deep file hierarchies (see https://github.com/dandi/dandiarchive/issues/728#issuecomment-856087098 for original discussion).

TODO:
- [ ] clarify this issue with better detail of what's going wrong

**Comment by yarikoptic** [comment]
My very wild guess - some path field string length limit in DB?

**Comment by waxlamp** [comment]
Closing in favor of #652.
