### ISSUE TITLE
Improve new user email

### ISSUE THREAD

**Issue by waxlamp** [dandi/dandi-api#361]
From @bendichter:

> This looks great! One small suggestion: instead of "Github helpdesk", I
would just call it a "helpdesk", and I would link to the discussion of that
repo, like this <https://github.com/dandi/helpdesk/discussions>, instead of
the repo landing page.

**Comment by satra** [comment]
it should link to the same link that we have on the page, which takes people to the choose option. i agree with not calling it Github helpdesk.

**Comment by yarikoptic** [comment]
#365 was merged into staging this didn't Auto close this (yet another good reason to avoid having staging branch)

**Comment by waxlamp** [comment]
We are no longer using the staging branch as part of the workflow for this repo. It, along with several other stale branches, are still there but I'm working on pruning them away.

**Comment by yarikoptic** [comment]
that is good to know (and worth removing `staging` if it is still there) -- I just provided explanation (based on the fact) why this issue was not auto-closed ;)
