### ISSUE TITLE
Add tinuous archive of the logs for introspection etc

### ISSUE THREAD

**Issue by yarikoptic** [dandi/dandi-api#369]
To facilitate archeological expeditions etc

- ATM we have only for dandi-cli at `dandi@drogon:~/cronlib/tinuous-logs/dandi-cli`
- should get a similar one for `dandi-api` nearby
- should use datalad and similar per-month subdatasets
- that tinuous IIRC wasn't updated for recent changes.
- might like to use a different layout a bit as I have done IIRC for datalad (on smaug)
- I think there are some artifacts built, so might archive them as well

**Comment by jwodder** [comment]
@yarikoptic The artifacts are Docker images that are only stored as artifacts in order to cut down on the amount of time spent building images.  I don't think they should be downloaded, as they are around 845 MB in size.

**Comment by jwodder** [comment]
tinuous set up with cronjob for dandi-api at `dandi@drogon:~/cronlib/tinuous-logs/dandi-api`.
