### ISSUE TITLE
FOI: contentUrls are not longer provided, broke backups2datalad setup

### ISSUE THREAD

**Issue by yarikoptic** [dandi/dandi-api#377]
I guess it is all for the ultimate goal of the mutable metadata records, but stripping away populating contentUrl " on the fly ", I believe is what broke https://github.com/dandi/dandisets/blob/master/tools/backups2datalad.py#L447 which needs those being populated for injection into git-annex.

Since I guess there is no way back now and we should just look forward for them to be populated whenever we migrate metadata records for new schema, this is probably just FOI (For our information) and I will need to workaround by manually crafting those urls if records we obtain from API server do not have them.

edit 1: and that would require querying S3 to get versionId's

**Comment by satra** [comment]
they should contain the urls but this is why asset metadata migration is needed. the assets. we have run into a bit of a chicken and egg situation here

**Comment by yarikoptic** [comment]
well -- no chicken/egg really: what we should have done is migrate metadata from DB (URLs, sha256 digest) into metadata records BEFORE turning off their auto-population on the fly.  Metadata schema version migration is kinda separate step IMHO since we did not freeze the archive for it and people might still be uploading and we need to make sure to not upload metadata extracted on a wrong (outdated on drogon) file. 
Now I also ended up without sha256 and since sha256 (not dandi etag) was used for git-annex keys, I think am doomed to compute etag on every file :-/

**Comment by yarikoptic** [comment]
well, may be I am wrong and don't need to do it for every file, if it is not changed from prior version of assets listing... still looking at it.

**Comment by yarikoptic** [comment]
anyways -- it seems that the script is indeed robust (after minor tune up) to lack of contentUrls and sha256.  I am now going through some representative dandisets (one at a time)  and updating them, then will flood with all the others.  The issue is non-issue, closing
