### ISSUE TITLE
set manifest location for draft versions to API server

### ISSUE THREAD

**Issue by satra** [dandi/dandi-api#378]
can we set the manifest location for a draft version to:

`https://api.dandiarchive.org/api/dandisets/<numeric id>/versions/draft/assets/`

**Comment by satra** [comment]
@dchiquito - it would be good to get this fix in. i'm just responding to someone and wanted to be able to point to this as the authoritative source of manifest information.

**Comment by satra** [comment]
@dchiquito - ping on this

**Comment by dchiquito** [comment]
@satra Can you check staging and confirm it's working correctly? I just created https://gui-staging.dandiarchive.org/#/dandiset/000031 and `manifestLocation` is set exactly how I would expect it.

However, dandisets like https://gui-staging.dandiarchive.org/#/dandiset/000027 already have a `manifestLocation` which is not overwritten. Now that this is in place any new requests with `manifestLocation` in them will have it stripped out, but any existing dandisets with erroneous draft `manifestLocation`s won't be updated.

**Comment by satra** [comment]
`manifestLocation` should be a server set property for both draft and published dandisets.

for draft it should always be overridden or set to what you have for 31. 
for published it should point to the published assets i think.

we can do a GET/PUT on 27 right to have it stripped out?

**Comment by dchiquito** [comment]
This was resolved properly by https://github.com/dandi/dandi-api/pull/429. Any change to a draft dandiset will set the manifestLocation to the correct value, and published dandisets have their manifestLocation set correctly.
