### ISSUE TITLE
performance of PUT request

### ISSUE THREAD

**Issue by satra** [dandi/dandi-api#384]
jon dataset 20 in 6 hours the script has only gone through about 1100 assets. (at this rate it will take about a day to finish).

- metadata extraction from the file locally (on drogon)
- metadata upload via PUT to the API

on instrumenting with timestamps, it seems that the largest cuplrit is the PUT request time.

```
[2021-07-01 16:02:56,538] INFO - Getting metadata
[2021-07-01 16:02:56,545] INFO - Finished getting metadata
[2021-07-01 16:02:56,545] INFO - updating: sub-701146932/sub-701146932_ses-703511851_icephys.nwb
[2021-07-01 16:03:13,678] INFO - Finished updating

[2021-07-01 16:03:13,679] INFO - Getting metadata
[2021-07-01 16:03:13,686] INFO - Finished getting metadata
[2021-07-01 16:03:13,686] INFO - updating: sub-701146932/sub-701146932_ses-703609929_icephys.nwb
[2021-07-01 16:03:31,137] INFO - Finished updating
```

**Comment by satra** [comment]
here is the code snippet

```python
            ul.info("Getting metadata")
            localmeta = get_meta(localpath, asset["digest"]["dandi:dandi-etag"])
            ul.info("Finished getting metadata")
            localmeta["path"] = asset["path"]
            localmeta["blobDateModified"] = asset["blobDateModified"]
            url = f"https://api.dandiarchive.org/api/dandisets/{dandiset}/versions/draft/assets/{asset['asset_id']}/"
            payload = {
            "metadata": localmeta,
            "blob_id": asset["blob_id"]
            }
            ul.info(f"updating: {asset['path']}")
            # print(url, payload)
            headers["Authorization"] = f"token {api_key}"
            if update:
                response = requests.request("PUT", url, json=payload, headers=headers)
                ul.info("Finished updating")
            if not response.ok:
                ul.error(response.text, url)
                couldnotupdate.append(asset)
```

**Comment by satra** [comment]
this issue is a function of the total number of assets, this particular one has 4500+

**Comment by yarikoptic** [comment]
posted in slack:  I think we should mediate it by
- turn off updates of assetsSummary
- finish upload of all tuned up metadata
- turn on updates of assetsSummary
- trigger recomputation of assetSummaries across all dandisets
- look into staggering of such jobs : #385

**Comment by satra** [comment]
we can also consider a design where the validation task for dandiset is added as a timed job, and the start of that is always N seconds into the future. each time an asset update comes in it punts that job to current time + N s. so if a bunch of assets coming in, this job will never run till time + N has expired after an asset. since most asset uploads are in batches, this should work.

**Comment by yarikoptic** [comment]
that is one of the ways to implement that staggering I had in mind, thus copied your comment @satra to https://github.com/dandi/dandi-api/issues/385#issuecomment-872583525 ;-)

**Comment by waxlamp** [comment]
This morning Daniel and I discussed a more organic approach to this as well, involving treating the assets summary computation as a prerequisite to publishing, with some extra quirks. I can go over the ideas the next time we speak face to face.

**Comment by satra** [comment]
Just an fyi that the summary is key to search via the gui and dlp, so it's not just a publishing thing.
