### ISSUE TITLE
"framework" to debounce some actions to trigger only one whenever no new requests come in

### ISSUE THREAD

**Issue by yarikoptic** [dandi/dandi-api#385]
there must be some correct web-development approach/term for it.  But for update of assetsSummary and later possibly DataLad repos, it is desired to not trigger those actions upon every asset update, but only after such requests "stop coming" or very explicitly triggered.  

PS I vaguely remember talking about this , but failed to find, might have been just a slack black hole but could be a duplicate (I failed to find)

ref #384

**Comment by yarikoptic** [comment]
@satra in https://github.com/dandi/dandi-api/issues/384#issuecomment-872581626

we can also consider a design where the validation task for dandiset is added as a timed job, and the start of that is always N seconds into the future. each time an asset update comes in it punts that job to current time + N s. so if a bunch of assets coming in, this job will never run till time + N has expired after an asset. since most asset uploads are in batches, this should work.

**Comment by waxlamp** [comment]
What you are describing is known as "debouncing" (originally from [electrical engineering](https://en.wikipedia.org/wiki/Switch#Contact_bounce) but I learned the term in context of web-based callback design, e.g. through [underscore](https://underscorejs.org/#debounce)). It's common engineering design to include a delay for when the action fires as well (as through the `wait` parameter of underscore's `debounce()` function).

**Comment by satra** [comment]
indeed. celery has a notion of countdown. as long as you can extract a task id for a specific operation, it should be possible to reschedule the operation.

**Comment by waxlamp** [comment]
@dchiquito, is this issue now moot?

**Comment by dchiquito** [comment]
Yep, debouncing was achieved by updating summaries in a task that runs every minute.
