### ISSUE TITLE
return validation status of an asset using a filter operation

### ISSUE THREAD

**Issue by satra** [dandi/dandi-api#396]
proposal is to add a parameter to getting assets that allows filtering based on validation status. this seems to be easier to do at the database level.

**Comment by waxlamp** [comment]
@satra ^^^

**Comment by satra** [comment]
this is now available. for example: https://api-staging.dandiarchive.org/api/dandisets/100978/versions/draft/assets/7ddc2ff6-16c5-4ede-a769-68cf03d18cb7/validation/
