### ISSUE TITLE
add a few more files to publish

### ISSUE THREAD

**Issue by satra** [dandi/dandi-api#399]
- [ ] add jsonld files (export the json metadata with extension jsonld)
- [ ] create a link (`collection.jsonld`) file that links dandiset id with all the asset ids. (this can be technically recovered from the two files, but would be good to just generate one).

collection.jsonld

```json
{ "@context": <same context as dandiset.jsonld>,
  "id": <same id as dandiset.jsonld>,
  "@type": "prov:Collection", 
  "hasMember": [comma-separated list of "dandiasset:<id>"]
}
```

**Comment by dchiquito** [comment]
@satra should the first file be called `metadata.jsonld` or `dandiset.jsonld` or something else? You only specified an extension

**Comment by satra** [comment]
should be called dandiset.jsonld and assets.jsonld (so just extension/format change)
