### ISSUE TITLE
Enable circle-ci?

### ISSUE THREAD

**Issue by yarikoptic** [dandi/dandi-api#4]
There is circle-ci setup cloned along.
I bet it is easy, but I  never dealt with setting up circle ci for a repo so I would appreciate if someone else (@satra?) would do it so we get PRs and on cron tested here.

**Comment by mgrauer** [comment]
How about we enable Circle-CI for now, until someone sets up github actions? @dchiquit had merged some PRs that didn't lint or pass tests in dandi-api repo, and we don't want to do that in the future. Enabling circle should be very quick as there is already a config file.

What is the reason to move from Circle to GitHub actions @satra (as referenced in #1) ?

I myself don't have a strong preference--as long GitHub actions can give us what we get from circle--other than getting CI setup ASAP and circle is already most of the way there (and our config is debugged) for this repo.

**Comment by mgrauer** [comment]
Circle is running for now. We will update to GitHub Actions at some point.
