### ISSUE TITLE
Update validation status to PENDING wherever possible

### ISSUE THREAD

**Issue by dchiquito** [dandi/dandi-api#407]
@dchiquito Could the server update the status as part of responding to the `POST .../assets/` or `PUT .../assets/{asset_id}/` request at the end of an upload?  Exactly what sort of requests trigger an asset validation job, anyway?

_Originally posted by @jwodder in https://github.com/dandi/dandi-cli/issues/706#issuecomment-877372380_

We should try to keep the validation status of assets and versions as up to date as possible. When performing an operation that will definitely trigger a validation eventually, we should mark assets/versions as PENDING.

**Comment by satra** [comment]
@dchiquito - does this mean the states here weren't implemented: https://github.com/dandi/dandi-api/blob/master/doc/design/publish-1.md#validation-process

**Comment by waxlamp** [comment]
@dchiquito what's the status on this?

**Comment by dchiquito** [comment]
This no longer applies. This was before we were using the scheduled job to compute asset summaries, so marking assets as `PENDING` wasn't strictly required. That is now how assets are queued for updates, so this has implicitly already been done.
