### ISSUE TITLE
remove duplicated assets ?

### ISSUE THREAD

**Issue by yarikoptic** [dandi/dandi-api#413]
Follow up to merged https://github.com/dandi/dandi-api/pull/412 which should (didn't review yet) prevent assets duplication in the future.  But we already have some dandisets with AFAIK duplicated assets e.g. https://gui.dandiarchive.org/#/dandiset/000108 @satra identified this issue on.

**Comment by waxlamp** [comment]
Yes, Daniel is already aware of this and will work to remove the dupes as soon as we are confident that the fix actually works.

**Comment by waxlamp** [comment]
Done.
