### ISSUE TITLE
does the user search taken active status into account

### ISSUE THREAD

**Issue by satra** [dandi/dandi-api#415]
when the user search endpoint is used, does it filter by internal db active status?

**Comment by satra** [comment]
and do we know what happens on the UI when a non-active user tries to log in? do we have some message to say please post an issue on github or email X?

**Comment by waxlamp** [comment]
> when the user search endpoint is used, does it filter by internal db active status?

Yes, it only returns users that have status `APPROVED` and have `is_active` set to true.

> and do we know what happens on the UI when a non-active user tries to log in? do we have some message to say please post an issue on github or email X?

There's a banner that says to wait for two business days for approval, and it lists `help@dandiarchive.org` as a contact email.

I'll close this issue, but please continue discussion as needed.
