### ISSUE TITLE
Establish integration testing with dandi-cli

### ISSUE THREAD

**Issue by yarikoptic** [dandi/dandi-api#42]
May be not right away if some breaking changes are still to be expected, but if not or just to be "friendly" to dandi-cli developers right away, it would be great to have a CI run (github actions are used in dandi-cli) which would run dandi-cli tests against the state of dandi-api changes. This way we would at least be made aware of changes in dandi-api which would break dandi-cli to proactively mitigate them.

**Comment by yarikoptic** [comment]
I think now is a good time -- `dandi-api` is stabilizing, and `dandi-cli` supports it. It would be unfortunate if changes in dandi-api would break dandi-cli.
We should add two runs test against released and master branch of `dandi-cli`.

**Comment by jwodder** [comment]
@yarikoptic Exactly what parts of dandi-cli should be run against the version of dandi-api under test?  How do we run dandi-api as a server for testing against?  Should the workflow runs just build the dandi-api Docker image and use it in place of the Docker Hub image for dandi-cli's tests?

**Comment by yarikoptic** [comment]
> @yarikoptic Exactly what parts of dandi-cli should be run against the version of dandi-api under test

 it should be all tests which use that docker compose fixture with a local instance of dandi-api



> How do we run dandi-api as a server for testing against? Should the workflow runs just build the dandi-api Docker image and use it in place of the Docker Hub image for dandi-cli's tests?

Yeap, Building/using docker image might be the easiest way forward which shouldn't require any change in dandi cli

**Comment by jwodder** [comment]
@yarikoptic Should the integration tests only run on pushes & pull requests or also on a schedule?
