### ISSUE TITLE
staging bucket permissions are different from the deployment one

### ISSUE THREAD

**Issue by yarikoptic** [dandi/dandi-api#425]
in that I can't really access any blob, or list the bucket

<details>
<summary>my attempts</summary> 

```shell
$> datalad ls s3://dandi-api-staging-dandisets/blobs/285/edf/285edfaa-f368-43e2-bf49-07539a869c4d
Connecting to bucket: dandi-api-staging-dandisets
[INFO   ] S3 session: Connecting to the bucket dandi-api-staging-dandisets anonymously 
[ERROR  ] Failed to download from s3://dandi-api-staging-dandisets/blobs/285/edf/285edfaa-f368-43e2-bf49-07539a869c4d given available credentials [base.py:_enter_credentials:340] (DownloadError) 

$> s3cmd ls s3://dandi-api-staging-dandisets/blobs/285/edf/285edfaa-f368-43e2-bf49-07539a869c4d
ERROR: /home/yoh/.s3cfg: None
ERROR: Configuration file not available.
ERROR: Consider using --configure parameter to create one.

$> s3cmd -c ~/.s3cfg-dandi-backup ls s3://dandi-api-staging-dandisets/blobs/285/edf/285edfaa-f368-43e2-bf49-07539a869c4d 
ERROR: Access to bucket 'dandi-api-staging-dandisets' was denied
ERROR: S3 error: 403 (AccessDenied): Access Denied

$> s3cmd ls s3://dandi-api-staging-dandisets/                                                                           
ERROR: /home/yoh/.s3cfg: None
ERROR: Configuration file not available.
ERROR: Consider using --configure parameter to create one.

```
</details>

on one hand -- it might be desired (thus could be argued to be a "feature" and closed) but I thought that having staging and deployment as similar as possible would be beneficial, thus IMHO preferable.

I have ran into this as my next step in https://github.com/dandi/dandi-api/issues/286#issuecomment-883606023 in trying to download a blob from https://dandi-api-staging-dandisets.s3.amazonaws.com/blobs/285/edf/285edfaa-f368-43e2-bf49-07539a869c4d

**Comment by waxlamp** [comment]
Indeed, the production bucket is world-readable by design. We can make the staging bucket this way also if it helps to carry out testing. I'd like to hear opinions from @satra, @dchiquito, and @brianhelba on what pitfalls may exist if we do so.

**Comment by satra** [comment]
if we clear out everything on some regular basis then perhaps. or when we support wasabi, perhaps then we enable public staging since egress is free.

**Comment by yarikoptic** [comment]
Note: benefit of having staging public is not for consumption, but for testing to parallel production. API urls (eg exposed via web ui) already provide access to those blobs. Disabling access at bucket level doesn't really make staging data non downloadable.

We should clean it out quite regularly anyways to not incur avoidable cost. I think before embargo we should have GC implemented first, which relates here as well

**Comment by yarikoptic** [comment]
> We can make the staging bucket this way also if it helps to carry out testing.

Let's do so?  or at least may be to allow LIST/GET on keys (I don't think we need to list the entire bucket content) -- needed to establish testing of the datalad'ification script.  Even if we had a unified interface to both minio and s3 (ref: https://github.com/dandi/dandi-api/issues/344) it would not test "as deployed", so we decided to proceed with (ab)using staging bucket.  But then ran into this issue of not being able to interact with it directly, as needed for git-annex, as we do with the non-staging one.
attn @jwodder

**Comment by dchiquito** [comment]
I see no objection to adjusting the staging bucket permissions. I plan on getting to that tomorrow.

**Comment by brianhelba** [comment]
I also see no problem with adjusting the staging bucket permissions to mirror production.

**Comment by yarikoptic** [comment]
Great! Thank you @dchiquito in advance

**Comment by yarikoptic** [comment]
BTW, while at it - make sure it is versioned bucket. Would allow to test GC say s3 level etc before bringing to production

**Comment by dchiquito** [comment]
@yarikoptic I updated the staging bucket to have the same permissions settings as production.
