### ISSUE TITLE
Error when trying to publish twice in a row

### ISSUE THREAD

**Issue by jwodder** [dandi/dandi-api#428]
I'm writing a test for the client that requires a Dandiset to have at least two different published versions, and so the publish endpoint is called on the draft version twice.  Unfortunately, the second time the endpoint is called (even after waiting for validity between publications), it fails with a 400 response with the message "Dandiset metadata or asset metadata is not valid", despite the fact that the same metadata was just used to produce a valid published version.

**Comment by mvandenburgh** [comment]
[The API was recently updated to prevent this](https://github.com/dandi/dandi-api/issues/290). The draft needs to be modified after the first publish in order to publish a second time.
