### ISSUE TITLE
scheduled-tasks design: needs a mechanism to allow for reasonable use in tests

### ISSUE THREAD

**Issue by yarikoptic** [dandi/dandi-api#431]
@jwodder's issue/question #428 made me realize that if https://github.com/dandi/dandi-api/blob/master/doc/design/scheduled-tasks.md (+ #423) is implemented "as is", it would make testing `publish/` in dandi-cli and elsewhere [*] against dandi-api would then take it many minutes if not hours to run, since for every publish we would need to wait for scheduled tasks to trigger (I guess waiting for status of validation to be not PENDING).

If we are to proceed that way, possible ways I see to mitigate (with preference on the first one):
- we would need to make the period of time (ATM 5 minutes?) configurable, so while running test instance of dandi-api we could set it e.g. to some few (2?) seconds instead.  Cons: possibly a bit more load on dandi-api instance; Pros: that should also allow  to test the "logic" of transitioning between states better, since with a tighter loop it would be easier to run into all kinds of race conditions I had been commenting on
- add extra end-point available to admin user(s) to force-trigger scheduled tasks without awaiting for the 5 minutes. This way we could hit the end point in tests right before triggering `publish`.  Cons: ad-hoc, requires tests logic customization which otherwise would not be used.

[*] we are about to establish it for datalad dandisets backup script

**Comment by waxlamp** [comment]
I think this has been solved--we now schedule validation tasks to run on the minute, which means this should no longer be a problem. Re-open if I have that wrong.
