### ISSUE TITLE
Remove AssetMetadata model

### ISSUE THREAD

**Issue by dchiquito** [dandi/dandi-api#433]
The original intent for AssetMetadata was to deduplicate metadata in the same way that blobs are deduplicated. This has turned out to be completely nonsensical, as metadata always includes asset specific information that is never shared between two assets.

Since there is no point to having AssetMetadata and it is obnoxious to deal with, we should remove it and just use a `metadata: JSONField` field directly on the Asset model.

**Comment by mvandenburgh** [comment]
This was resolved in #464.
