### ISSUE TITLE
extend top level /assets/ end-point to mirror dandisets_version ones

### ISSUE THREAD

**Issue by yarikoptic** [dandi/dandi-api#436]
trigger for the request: https://github.com/dandi/dandi-cli/issues/723#issuecomment-884920772 i.e. inability to get asset metadata (to e.g. decide either it was modified or might be the same IIRC) to make `dandi download` handle top level `/assets/<asset_id>/download/` end points.

I think there should be
- `GET /assets/{asset_id}/` -- get metadata (of immediate need)
- `GET /assets/{asset_id}/validation/` -- forgot what it does exactly (triggers validation? returns validation status?) and swagger doesn't tell but I guess there is no reason to not have it at top level as well

**Comment by yarikoptic** [comment]
@waxlamp WDYT would be ETA for this? 
if long -- we would need a workaround at dandiarchive level to e.g. switch back to provide `dandiset_version` based /assets download urls instead of top level -- otherwise (without metadata on assets) `dandi-cli` cannot handle urls users get from web ui, and do its due diligence (check checksum, mtime, etc) and thus support these new endpoints "properly"

**Comment by waxlamp** [comment]
It should be pretty easy to add this. I will do so soon, or ask Daniel to work on it.

**Comment by waxlamp** [comment]
@dchiquito: there are a bunch of tests failing, where the API is giving a 200 instead of a 302. Any idea what's going on?

**Comment by waxlamp** [comment]
@yarikoptic, can you and @jwodder test this functionality on staging through the necessary changes in dandi-cli? If it works as expected, we can do a release to get it into production.

**Comment by yarikoptic** [comment]
it should be possible, I have updated https://github.com/dandi/dandi-cli/issues/723
