### ISSUE TITLE
potential additional steps for draft datasets

### ISSUE THREAD

**Issue by satra** [dandi/dandi-api#445]
to bring draft datasets to some level of findability and usability, we should:

1. "publish" using a cron-job to our dandisets prefix (this will also ensure that we can reconstruct the data archive from the s3 bucket in case something happens (subject to draftness changes between cron invocations). this may be tied with changes to validation invocations. 
2. mint a draft doi from the production datacite server. this may be helpful to labs seeking to include a doi at the point of article submission. we would only publish the doi when the publish button is actually pressed.

**Comment by waxlamp** [comment]
What is the benefit of publishing to a false prefix for findability/usability? I would imagine the search mechanisms we wish to ultimately have could simply work on all dandisets, regardless of draft/published status, without having to go through the motions of publishing them somewhere.

**Comment by satra** [comment]
>  false prefix

not sure i understand what this means.

the publish of draft datasets to s3 is to help satisfy aws criteria for the open dataset program.

**Comment by waxlamp** [comment]
> > false prefix
> 
> not sure i understand what this means.
> 

Sorry, I assumed that by "dandisets prefix" you meant a separate publishing area that is cordoned off from "actual" published versions. That's what I meant by "false prefix".

> the publish of draft datasets to s3 is to help satisfy aws criteria for the open dataset program.

Ah ok. Is this a matter of findability _within_ the sponsored bucket, or via search engines going through the archive site?

**Comment by satra** [comment]
> dandisets prefix

ah i realize that i may be the only person that uses object prefixes on s3 as a noun :) 

this would be the s3 prefix that we are using for publishing dandisets. so no change to the location, just that we would also run the s3 publishing step (potentially sans validation or doi) for draft dandisets.

> Is this a matter of findability within the sponsored bucket

yes.

**Comment by yarikoptic** [comment]
Re doi for draft - I think it might make sense to mint/update doi pointing to latest (draft or release) similarly to what zenodo does (they don't have draft though, so points to latest release)

**Comment by waxlamp** [comment]
@satra, is this still valid? I think our draft dandisets are already findable--in fact, too findable such that we moved to restrict empty dandisets from display in the portal by default.

**Comment by satra** [comment]
1 has been implemented for draft dandisets on the bucket. 2 would be nice to consider, but may require some fundamental changes given our doi scheme. closing for now.
