### ISSUE TITLE
update citation to use doi for published version

### ISSUE THREAD

**Issue by satra** [dandi/dandi-api#462]
@yarikoptic - any reason not to use the doi in the citation for the published version? wouldn't that be more standard for publication (also see zenodo's citation).

**Comment by yarikoptic** [comment]
Sure we need to include doi in the citation for published version now that we have them,  I am all for it

**Comment by waxlamp** [comment]
@satra, I'm unclear on what needs to be done. This sounds like a frontend issue?

**Comment by satra** [comment]
this is an api issue. the citation field generation has to be replaced with the doi url when publishing.

**Comment by waxlamp** [comment]
Closed via #467
