### ISSUE TITLE
Assets Summary is not always present

### ISSUE THREAD

**Issue by dchiquito** [dandi/dandi-api#466]
Assets Summary is not present on https://gui-staging.dandiarchive.org/#/dandiset/000026/draft.
Assets Summary is also not present if you start on https://gui-staging.dandiarchive.org/#/dandiset/000026/draft and click one of the published versions. However, if you click one of the published versions, then click a different published version, Assets Summary shows up as an empty field.

https://gui-staging.dandiarchive.org/#/dandiset/000026 only contains a single file without any of the fields that are aggregated into the Assets Summary, so its possible that this is just a problem with rendering null data.

**Comment by waxlamp** [comment]
I'm not able to reproduce. I assume this has been fixed since; additionally, this may become moot with the DLP redesign work that's going on now. I'll close, but please re-open if you can demonstrate the problem on a different dandiset or with a different repro.
