### ISSUE TITLE
blobs_digest_create (AKA POST /blobs/digest) - support 'dandi:sha2-256' algorithm

### ISSUE THREAD

**Issue by yarikoptic** [dandi/dandi-api#468]
pretty much a replacement for a closed #135 , so let me answer @waxlamp question

> @yarikoptic can you clarify whether this is still needed? It sounds like you are asking for a content-addressable store for the blobs, but I'm not clear on why accessing a dandiset's asset blobs via asset IDs is a problem.

it is desired to provide user convenience and ability to integrate with external services (such as https://github.com/flatironinstitute/kachery) which operate based on a commonly used (unlike dandi-etag) sha256 checksum.

For some reason I thought that we already support fetching blobs by sha256 (well -- #135 was closed ;-)), so I desperately tried to get a blob while trying different "sha256" algorithm specifications, but then looked into the code: https://github.com/dandi/dandi-api/blob/master/dandiapi/api/views/upload.py#L80 

```python
    if request_serializer.validated_data['algorithm'] != 'dandi:dandi-etag':
        return Response('Unsupported Digest Algorithm', status=400)
```
to realize that it is not the case. It is not urgent, but I think because AFAIK we do have sha256 stored for blobs we should make it possible to request a blob by its sha256.

**Comment by jwodder** [comment]
@yarikoptic @dchiquito This isn't strictly necessary for this issue, but why is a "fetch" operation implement via a POST endpoint?  Wouldn't it make more sense for it to be a GET with the algorithm and value passed as query parameters?

**Comment by dchiquito** [comment]
I see no reason for that to be a POST, feel free to change it to a GET.

**Comment by yarikoptic** [comment]
> I see no reason for that to be a POST, feel free to change it to a GET.

is this endpoint used already in some CLI? I don't think we use it in dandi-cli and `git grep blobs` in dandiarchive comes empty.

**Comment by jwodder** [comment]
@yarikoptic It is used in dandi-cli: https://github.com/dandi/dandi-cli/blob/05b956019bfe4cdc5eb8af114f99d8562709e082/dandi/dandiapi.py#L1057

**Comment by yarikoptic** [comment]
> @yarikoptic It is used in dandi-cli: https://github.com/dandi/dandi-cli/blob/05b956019bfe4cdc5eb8af114f99d8562709e082/dandi/dandiapi.py#L1057

what would be our migration path then to support (at least for a while both staging and main instance, since dandi-api still does not provide a usable `version`)?  try `GET` and if not there (405?) then try `POST`?

PS FWIW -- I also would vote it to have this `GET` instead of `POST`

**Comment by jwodder** [comment]
@yarikoptic 

> what would be our migration path then to support (at least for a while both staging and main instance, since dandi-api still does not provide a usable version)? try GET and if not there (405?) then try POST?

That seems like the best option.

**Comment by dchiquito** [comment]
It's pretty easy to allow both `GET` and `POST` on the endpoint. We could do that temporarily in this PR, update the CLI to use `GET`, then in a while remove the `POST` after people have had a chance to bump their dandi-cli version.
