### ISSUE TITLE
allow (with force=True, admin-only?) deletion of dandisets with published versions

### ISSUE THREAD

**Issue by yarikoptic** [dandi/dandi-api#476]
ATM the need primarily for use of staging archive for testing of https://github.com/dandi/dandisets/pull/55 but eventually we might need this functionality to prune bogus/compromised/etc dandisets anyways.

**Comment by yarikoptic** [comment]
Dear @jwodder, please take a stab at furnishing such a PR.  I will surrender to @dchiquito 's suggestion of having a dedicated `destroy` end-point instead of just "enhancing" `DELETE`. https://github.com/dandi/dandi-api/blob/HEAD/dandiapi/api/views/dandiset.py#L136 has example for user being admin check.

**Comment by jwodder** [comment]
@yarikoptic @dchiquito How should this "destroy" method be accessed via the API?  As `DELETE .../versions/{version}/`, `POST .../versions/{version}/destroy/`, or something else?

**Comment by waxlamp** [comment]
> @yarikoptic @dchiquito How should this "destroy" method be accessed via the API? As `DELETE .../versions/{version}/`, `POST .../versions/{version}/destroy/`, or something else?

IMO it should be `DELETE .../versions/{version}`.

**Comment by yarikoptic** [comment]
oh, right -- so then it would be a duty of the client to just to go through all versions, DELETE them and then DELETE the "top level" (would not even fail since there would be no published entries) dataset , right?

**Comment by waxlamp** [comment]
> oh, right -- so then it would be a duty of the client to just to go through all versions, DELETE them and then DELETE the "top level" (would not even fail since there would be no published entries) dataset , right?

I think this is correct, though I am not sure what you mean by "not even fail". If the dandiset has no published versions, then `DELETE /dandiset/{dandiset}` would succeed. Otherwise, you would need to `DELETE` all the versions first, as you said. (And, additionally, `DELETE .../versions/draft` should always result in an error.)

**Comment by yarikoptic** [comment]
> I think this is correct, though I am not sure what you mean by "not even fail". If the dandiset has no published versions, then `DELETE /dandiset/{dandiset}` would succeed. Otherwise, you would need to `DELETE` all the versions first, as you said. (And, additionally, `DELETE .../versions/draft` should always result in an error.)

yeap, that is what I meant by "not even fail" -- not error out upon DELETE as there would be no published versions left.

> (And, additionally, DELETE .../versions/draft should always result in an error.)

Great point, thank you @waxlamp ! Although we did envision (somewhere/sometime) ability to "archive" dandisets, so `draft` is removed,  only published versions exist -- so no further changes to dandiset could be done.  But that would require review of the design etc, so indeed for now the only safe bet is to refuse explicit deletion of `draft`.

**Comment by waxlamp** [comment]
> > I think this is correct, though I am not sure what you mean by "not even fail". If the dandiset has no published versions, then `DELETE /dandiset/{dandiset}` would succeed. Otherwise, you would need to `DELETE` all the versions first, as you said. (And, additionally, `DELETE .../versions/draft` should always result in an error.)
> 
> yeap, that is what I meant by "not even fail" -- not error out upon DELETE as there would be no published versions left.
> 

👍🏾 

> > (And, additionally, DELETE .../versions/draft should always result in an error.)
> 
> Great point, thank you @waxlamp ! Although we did envision (somewhere/sometime) ability to "archive" dandisets, so `draft` is removed, only published versions exist -- so no further changes to dandiset could be done. But that would require review of the design etc, so indeed for now the only safe bet is to refuse explicit deletion of `draft`.

I agree that this is a separate feature. Even then, I imagine we would do something like `PUT` a boolean value to `/dandisets/{dandisets}/archive` in order to make the draft version disappear, but that is quite different from the `DELETE` actions we're discussing here.
