### ISSUE TITLE
dandiset metadata dateCreated returns None

### ISSUE THREAD

**Issue by bendichter** [dandi/dandi-api#485]
```python
from dandi.dandiapi import DandiAPIClient

with DandiAPIClient() as client:
    dandiset = next(client.get_dandisets())
    print(dandiset.created)
    metadata = dandiset.get_metadata()
    print(metadata.dateCreated)

2020-03-15 22:56:55.655000+00:00
None
```

**Comment by dchiquito** [comment]
I'm assuming that the `dateCreated` for all draft and published versions of a dandiset should be the date the dandiset was first created, and not the date that that particular version was created.

**Comment by yarikoptic** [comment]
I think so. Pretty much set once when a new dandiset is created. Ping @satra
