### ISSUE TITLE
"Asset matching query does not exist" errors pop up in the logs

### ISSUE THREAD

**Issue by yarikoptic** [dandi/dandi-api#486]
which leads to

```
1365203836443738138     2021-08-20 02:39:41     2021-08-20 02:39:41     6519188732      dandi-api       54.235.113.36   Local7  Info    app/web.1       [02:39:41] ERROR    Internal Server Error: /api/assets/f841afd9-e9d9- log.py:224\n
1365203836443738139     2021-08-20 02:39:41     2021-08-20 02:39:41     6519188732      dandi-api       54.235.113.36   Local7  Info    app/web.1                           408c-95b2-a9d31543c635/download/                            \n
```

Since GC is not yet in place, I wonder how that could happen... the only things I thought of
- staging instance web ui managing to provide URLs to main instance, but it is not the case -- all good there, urls point to api-staging and that one redirects to staging bucket urls.  
- is a mix up between staging and main instances, but that asset uuid is not on staging either.  
- it is not tests since such errors aren't anyhow regular
- Sure thing could be a user just trying random UUIDs 

so should we just assume it was some user trying random UUIDs or there could be more to the story?

**Comment by dchiquito** [comment]
I don't think we have any way to determine what a client was trying to accomplish with that request, so I don't think we can resolve this particular UUID not existing.

However, it definitely should be returning a 404, not a 500. I will patch that.
