### ISSUE TITLE
Some way for users to set first name / last name in dev environment

### ISSUE THREAD

**Issue by mvandenburgh** [dandi/dandi-api#495]
https://github.com/dandi/dandiarchive/pull/850#discussion_r694296281

Right now the Django server infers the user's first and last name from their `SocialAccount` object. However, `SocialAccounts` are not used in local dev environments so first name and last name are always blank. 

There should be some way to set a user's first and last name locally. This would be particularly useful for e2e testing purposes.

**Comment by waxlamp** [comment]
I do this currently by editing the name fields in the Django admin console. Is that "the" way to do it? Does that mean it would require updating the `User` model from the web app?

**Comment by dchiquito** [comment]
The admin console is indeed probably the correct way to do this manually. Finding a way to do this well for automated test data is a thornier issue

**Comment by yarikoptic** [comment]
IMHO largely boils down to establishing API endpoints to "manipulate" users metadata etc as brought up in https://github.com/dandi/dandi-api/pull/496#discussion_r701392217 .

**Comment by waxlamp** [comment]
> IMHO largely boils down to establishing API endpoints to "manipulate" users metadata etc as brought up in [#496 (comment)](https://github.com/dandi/dandi-api/pull/496#discussion_r701392217) .

I'm against establishing these endpoints if they're only needed for admin purposes such as this. I believe we could solve this specific problem by changing the admin scripts for adding users to the system.

**Comment by yarikoptic** [comment]
not unlike metadata IIRC, users would be able to change their user record/metadata (e.g. name, possibly later ORCID ID etc), while admins would be able to change everyone's.  Hiding user management behind some completely separate admin interface would IMHO make it hard(er) for admins to do any user management. IMHO django interface should be left only for "rare/critical" interactions.

**Comment by waxlamp** [comment]
I guess I see this as falling under "rare/critical". I want to expose server features that are useful and expected for ordinary users to carry out. This issue is about dev accounts and how to get a real name associated with those. Unless there's a credible demand for ordinary users to change their system names (rather than just pulling that info from GitHub), I'd rather not go down that path.

**Comment by waxlamp** [comment]
My feelings on this are strengthened by the difference between "username supplied by GitHub" and "dandiset metadata"--the latter is directly in DANDI's bailiwick, while the former is quite far off to the side.

**Comment by yarikoptic** [comment]
Re GitHub: Do we sync name from GitHub periodically or only during account creation?

**Comment by waxlamp** [comment]
> Re GitHub: Do we sync name from GitHub periodically or only during account creation?

AFAIK, only during account creation, but @dchiquito would probably know better than me.

To answer the obvious next question: I still don't think a user-facing API for changing their display name within DANDI is called for here. If there are any problems with names, we can fix these sorts of things in a one-off manner in response to individual complaints using the Django admin console.

**Comment by yarikoptic** [comment]
FWIW, check resent user registration emails - many if not most didn't have name, so for them I guess they see ?? In the icon for the login and have no means to change that. I don't think it is a nice UX

**Comment by waxlamp** [comment]
Agreed. In that case, perhaps we should be showing their GitHub username, email address, or an initial thereof.

**Comment by dchiquito** [comment]
FWIW from what I can tell `extra_data` is actually refreshed on every login.

**Comment by waxlamp** [comment]
I believe this can be closed. In dev, we can set names directly through the admin console; in prod, we are now collecting names from people for use in the UI, communications, contact person records, etc.
