### ISSUE TITLE
consistent zone information

### ISSUE THREAD

**Issue by yarikoptic** [dandi/dandi-api#497]
Sorry, I have not followed up more in time in https://github.com/dandi/dandi-api/pull/492#issuecomment-902990631 and was awaiting for feedback from @jwodder .

#492 switched from using `datetime.datetime.utcnow()` (which provides no time zone , but some end points were happily reporting `Z` [millitary time zone](https://en.wikipedia.org/wiki/List_of_military_time_zones)) to `datetime.datetime.now(datetime.timezone.utc)` which started to add `+00:00` zone information.

I am yet to grasp where it was added and where it was not, and what effect it would have on returned metadata. At least for existing dandisets I see

```
$> curl --silent https://api.dandiarchive.org/api/dandisets/000003/versions/ | jq -r '.results[] | "\(.created) \(.modified)"'
2020-03-15T22:56:55.655000Z 2021-08-12T14:48:45.203390Z
2021-08-12T14:48:45.032118Z 2021-08-12T14:48:45.186427Z

$> curl --silent https://api-staging.dandiarchive.org/api/dandisets/000003/versions/ | jq -r '.results[] | "\(.created) \(.modified)"'
2021-05-07T20:12:29.968755Z 2021-08-13T19:02:42.311142Z
```

and for newly created on staging I also see
```
$> curl --silent https://api-staging.dandiarchive.org/api/dandisets/000170/versions/ | jq -r '.results[] | "\(.created) \(.modified)"'   
2021-08-24T14:58:32.661052Z 2021-08-24T14:58:34.088973Z
```

So the opening question(s) to @dchiquito:

do those changes only affect internal to DB stored datestamps (and otherwise -- returned with military Z zone spec) or will be also effecting some (but not all per above observation) date stamps returned in metadata?

**Comment by dchiquito** [comment]
That change impacts any dates saved in metadata. All of the dates in https://api-staging.dandiarchive.org/api/dandisets/000026/versions/0.210824.1946/ have `+00:00` appended. 

The dates that use `Z` are dates that are stored in Django DB columns: https://api-staging.dandiarchive.org/api/dandisets/000026/versions/0.210824.1946/info/ `created` and `modified`. You'll notice that everything under `metadata` uses `+00:00`.

Both formats are valid representations of UTC timestamps, any library that parses ISO formats should accept either.

**Comment by yarikoptic** [comment]
Even though they are both "valid", why to have them varying, I would have preferred a consistent zone representation across all datestamps, which could have been achieved by simply adding `Z` to that `utcnow()`

**Comment by waxlamp** [comment]
It's true that appending `Z` is equivalent to appending `+00:00`, but now that it's done I think we should fall back on the fact that indeed both formats express precisely the same semantics. Let's let these timestamps be machine readable and not worry about textual consistency.
