### ISSUE TITLE
Delete/Cleanup Draft DOIs whenever removing versioned dandiset

### ISSUE THREAD

**Issue by yarikoptic** [dandi/dandi-api#501]
Follow up to  PR #480 . I have noticed that we accumulated 371 DOIs on https://doi.test.datacite.org/repositories/dartlib.dandi/dois by running tests (ab)using 

- [ ] Deletion introduced in #480 should add an out-off-band job to remove a DOI found in that dandiset version metadata.  `Findable` DOIs cannot be removed, so we would not even try I guess, but all the `Draft` (which we populate in staging as far as I see it from those 371) could and should be removed 
- [ ] clean up already existing Draft DOIs on doi.test.datacite.org

ref: https://github.com/dandi/dandischema/issues/7

**Comment by jwodder** [comment]
@yarikoptic Can I get a list of (or a way to find) the DOIs created by the tests?  The link in your comment just redirects me to https://doi.test.datacite.org.

**Comment by yarikoptic** [comment]
you should be able to get a list of all DOIs via API https://support.datacite.org/docs/api  - I think it is ok to kill all "Draft" ones there or just the ones with "John Wodder" as the author

**Comment by jwodder** [comment]
@yarikoptic That only seems to return "findable" DOIs, and there doesn't seem to be a way to change that.  Querying https://api.test.datacite.org/dois/?query=dandi just returns results from the production Dandi Archive, and changing the query string to "Wodder" returns nothing.

**Comment by yarikoptic** [comment]
- odd... thought that `curl https://api.test.datacite.org/dois/?client-id=dartlib.dandi` may be would list them but seems not.  
- please try whenever authenticated to the instance
- if still no luck - please reach out to datacite asking for the clarification, since after all doc for endpoint says "List **all** DOIs" (accent mine) on https://support.datacite.org/reference/dois-1#list-all-dois

**Comment by yarikoptic** [comment]
worse comes to worse -- we can just crawl that https://doi.test.datacite.org/repositories/dartlib.dandi/dois?state=draft once, and parse them out and delete.

**Comment by jwodder** [comment]
@yarikoptic What are the credentials for the instance?

**Comment by jwodder** [comment]
@yarikoptic OK, using the credentials you sent, the API now returns draft DOIs.  However, I'm not sure what to search for in order to get the 371 results you got.  If I search for "Wodder", I get 339 results, and if I search for "dandi" with a state of "draft", I get 388 results.  There doesn't seem to be anything distinguising the Dandi staging DOIs from the Dandi production DOIs.

**Comment by yarikoptic** [comment]
production DOIs have different prefix. production `10.48324`, staging (test.) `10.80507`.  I would not "search" but request  all and filter "manually"

**Comment by jwodder** [comment]
@yarikoptic Do you mean list *all* draft DOIs and only operate on the ones with a "10.80507" prefix?  Because there are 233,561 draft DOIs, which means nearly 10,000 GET requests to get all the pages, and the server isn't very fast.

**Comment by jwodder** [comment]
@yarikoptic Actually, it turns out that isn't even an option.  Once the API gets past page 400, it starts returning the same page of items over & over, and the first 400 pages only contain 48 dandi-staging DOIs.

**Comment by yarikoptic** [comment]
Yikes, please report this bug you datacite.

**Comment by jwodder** [comment]
@yarikoptic Reported.  They don't seem to have a bug tracker, so I e-mailed the support address.

**Comment by jwodder** [comment]
@yarikoptic I've found that I can get all dandi-staging draft DOIs via a request to https://api.test.datacite.org/dois?prefix=10.80507&state=draft, but that seems to include some DOIs that weren't created by the backups2datalad tests.  Exactly what criteria should I use for deciding what DOIs to delete?

**Comment by yarikoptic** [comment]
Awesome!
In the first pass (well -- after https://github.com/dandi/dandi-api/pull/504 is merged or we would need to redo it again and again) - just remove the ones with you as the author, I think that would account for the majority.
Then I think we should remove all Draft DOIs associated with dandi-staging since why to pollute that space and/or rely on something which might disappear any moment (I don't think there are any guarantees on their persistence on test instance).
@dchiquito @djarecka (just to make sure) - do you have any DOIs on test instance of datacite which you need to keep (for tests etc)?

**Comment by yarikoptic** [comment]
note: "Publish" on testing instance creates "Draft" DOIs for published dandisets, e.g. https://gui-staging.dandiarchive.org/#/dandiset/000020 got https://doi.test.datacite.org/dois/10.80507%2Fdandi.000020%2F0.210830.2001 published by @mvandenburgh yesterday. BUT those DOIs do not point to some "staging redirector" so not forwarding to correct location on gui-staging anyways.  I wonder if there is a value in keeping those.

**Comment by djarecka** [comment]
I believe I don't use any in automatic tests. I think all my test that use it, should create a new one and clean after the test is done

**Comment by jwodder** [comment]
@yarikoptic Now that the PR has been merged, should I go ahead and delete the test DOIs?

**Comment by yarikoptic** [comment]
Yes, please

**Comment by jwodder** [comment]
@yarikoptic 175 draft DOIs under 10.80507 with me as the author deleted.

**Comment by yarikoptic** [comment]
awesome.  I still see 228 total and some of yours such as

Text Dandiset Dataset
John Wodder,
Neural Data published 2021 via DANDI Archive
A test text Dandiset
Created August 30, 2021, 13:47:39 UTC. Draft
10.80507/dandi.000198/0.210830.1347

is it taking datacite awhile to somehow react  or those were missed?

**Comment by jwodder** [comment]
@yarikoptic I'm guessing it's taking datacite a while to process the deletions.  If I query the API using the same query used for the deletions, I currently get 164 results.
