### ISSUE TITLE
Settings check in `create_doi` uses wrong logic?

### ISSUE THREAD

**Issue by jwodder** [dandi/dandi-api#503]
Shouldn't these `or`'s be `and`'s here?  I assume we only want to POST if *all* of the settings are set.

https://github.com/dandi/dandi-api/blob/77a30b2c0c3dcf057a1088512128ceccd97d26ca/dandiapi/api/doi.py#L31-L36

**Comment by yarikoptic** [comment]
yeah -- `or` makes no sense to me here. @dchiquito ?

**Comment by dchiquito** [comment]
My thinking was that DOIs will not work if any of those values are absent. If a user sets any of them, they presumably expect to publish DOIs. If a user were to forget one of the settings and I used `and` here, the DOI would simply not publish, leaving the user scratching their head. This way, there is at least a 500 error if a setting is accidentally omitted. 

I think the UX for forgetting one of the settings could be better than that though.

**Comment by waxlamp** [comment]
> My thinking was that DOIs will not work if any of those values are absent. If a user sets any of them, they presumably expect to publish DOIs. If a user were to forget one of the settings and I used `and` here, the DOI would simply not publish, leaving the user scratching their head. This way, there is at least a 500 error if a setting is accidentally omitted.
> 
> I think the UX for forgetting one of the settings could be better than that though.

Would it be better to explicitly raise a 4xx error if all of the values aren't set?

**Comment by yarikoptic** [comment]
We are taking about "deployment user" here, right?
Then IMHO it should be checked once upon start of the dandi-api that if settings.DANDI_DOI_API_URL is set all other 3 are set, and error out of they aren't . Here just use settings.DANDI_DOI_API_URL as an indicator that this deployment should mint DOIs

**Comment by dchiquito** [comment]
Turns out Django has a handy way to add system checks, I added one that verifies this in #508
