### ISSUE TITLE
Investigate S3 bucket-to-bucket copy (or move)

### ISSUE THREAD

**Issue by yarikoptic** [dandi/dandi-api#515]
In the context of embargo (https://github.com/dandi/dandi-api/issues/158) and for an alternative implementation of having a dedicated separate (private) bucket (so different from #510 ) we need to investigate 

- speeds of transfer within S3 between buckets in our zone
- is there S3 API call for "transfer" (copy and/or move) which performs the transfer without traffic going through the initiating server
  -  is ETag getting updated?
  - can we instruct on chunk sizes so ETag is matched?

**Comment by waxlamp** [comment]
I found this page that has some good information: https://aws.amazon.com/premiumsupport/knowledge-center/move-objects-s3-bucket/

The work proposed in this issue will come up naturally in implementing the unembargo workflow. As such, I'd like to close this issue.
