### ISSUE TITLE
Admin pages not loading

### ISSUE THREAD

**Issue by dchiquito** [dandi/dandi-api#539]
Some admin pages like https://api.dandiarchive.org/admin/api/version/556/change/ fail to load with a Heroku timeout error. I suspect the issue is that the Versions page is trying to show an unpaginated list of all the Assets in the Version, which is problematic for Versions with lots of Assets.

**Comment by waxlamp** [comment]
This should be resolved by #545.

@mvandenburgh, if that is true, can you add a `Closes` statement to that PR?

**Comment by mvandenburgh** [comment]
> I suspect the issue is that the Versions page is trying to show an unpaginated list of all the Assets in the Version, which is problematic for Versions with lots of Assets.

I don't think this is it. Even Versions with zero Assets fail to load, such as https://api.dandiarchive.org/admin/api/version/553/change/

**Comment by waxlamp** [comment]
Hm. What does the server log show?

**Comment by mvandenburgh** [comment]
This was closed in error #658
