### ISSUE TITLE
failing tests when run with django container: manifestLocation

### ISSUE THREAD

**Issue by djarecka** [dandi/dandi-api#553]
some tests from `dandiapi/api/tests/test_version.py` are failing when run with docker, i.e. `docker-compose run --rm django tox -e test dandiapi/api/tests/test_version.py`

Can paste entire error message, but I think all have issues with `mannifestLocation`:

```
E       AssertionError: assert {'@context': ...02434915, ...} == {'@context': ...02434915, ...}
E         Omitting 29 identical items, use -vv to show
E         Differing items:
E         {'manifestLocation': ['http://minio:9000/test-dandiapi-dandisets/test-prefix/dandisets/000067/0.211006.0154/assets.yaml']} != {'manifestLocation': ['http://localhost:9000/test-dandiapi-dandisets/test-prefix/dandisets/000067/0.211006.0154/assets.yaml']}
```

**Comment by djarecka** [comment]
yes, this is pretty consistent for multiple tests:
```
FAILED dandiapi/api/tests/test_version.py::test_published_version_metadata_computed 
FAILED dandiapi/api/tests/test_version.py::test_version_publish_version[draft]
FAILED dandiapi/api/tests/test_version.py::test_version_publish_version[published]
FAILED dandiapi/api/tests/test_version.py::test_version_rest_publish[draft]
FAILED dandiapi/api/tests/test_version.py::test_version_rest_publish[published]
```

**Comment by dchiquito** [comment]
The difference is in the minio base URL: `http://minio:9000/...` vs. `http://localhost:9000/...`. When running in docker, docker-compose automatically registers a local domain for each container, so you would need to send Minio requests to `minio:9000`. When running natively, docker is not there to do this networking, so all the services are running on `localhost`.
