### ISSUE TITLE
Give dandisets_versions_assets_list query parameters for controlling the sort order

### ISSUE THREAD

**Issue by jwodder** [dandi/dandi-api#563]
Feature request: The `/dandisets/{versions__dandiset__pk}/versions/{versions__version}/assets/` endpoint should take one or more query parameters for controlling the order in which the assets are returned.  To borrow from the GitHub API, the parameters could be `sort=<field name>` and `direction=<"asc" or "desc">`.  Fields that users would likely want to sort on include "created", "modified", and "path".

**Comment by waxlamp** [comment]
Thanks @jwodder. What do you plan to do with this prospective feature?

**Comment by waxlamp** [comment]
Right, I think it's a matter of what order the DB yields rows in. I think this is a reasonable feature to have so we'll look into it.
