### ISSUE TITLE
Add an API endpoint for listing the authenticated user's dandisets

### ISSUE THREAD

**Issue by jwodder** [dandi/dandi-api#583]

**Comment by waxlamp** [comment]
@dchiquito, could you weigh in on that TODO? The `user=me` mode seems fine to me.

I'm going to close this, @jwodder, but please re-open if the solution discussed upthread isn't sufficient.

**Comment by dchiquito** [comment]
I think the `user=me` solution is reasonable, I was aiming the TODO at the way `get_queryset` was using the request method/query parameters to do filtering. It seems a little questionable to me, but I have yet to find a better way to do it.

**Comment by waxlamp** [comment]
> I think the `user=me` solution is reasonable, I was aiming the TODO at the way `get_queryset` was using the request method/query parameters to do filtering. It seems a little questionable to me, but I have yet to find a better way to do it.

Could you file an issue that refers to the TODO so that we've captured your unease in the tracker?

**Comment by dchiquito** [comment]
https://github.com/dandi/dandi-api/issues/670
