### ISSUE TITLE
create: should populate identifier

### ISSUE THREAD

**Issue by yarikoptic** [dandi/dandi-api#63]
ATM creation of new dandiset via 'Create' button (at least that is what I did) does not populate `identifier` (only name and description), which then leads to `dandi-cli` downloaded `dandiset.yaml` (which is just a metadata record)` lack that identifier information.  Should look like
```
identifier:
  propertyID: DANDI
  value: '000009'
```
AFAIK according to our current schema and samples of converted dandiset level metadata in  https://github.com/dandi/dandi-api-datasets.git

**Comment by AlmightyYakob** [comment]
It looks like this also applies to the `name` field in the same way, so I might address that along with this.

**Comment by AlmightyYakob** [comment]
> Should look like
> 
> ```
> identifier:
>   propertyID: DANDI
>   value: '000009'
> ```

@satra https://github.com/dandi/dandi-cli/pull/348 will change this to look like:
```
identifier: 'DANDI:000009'
```

Correct?

**Comment by satra** [comment]
@AlmightyYakob - yes.
