### ISSUE TITLE
JSON objects in zarr checksums should have "md5" before "path"

### ISSUE THREAD

**Issue by jwodder** [dandi/dandi-api#631]
[The zarr docs](https://github.com/dandi/dandi-api/blob/master/doc/design/zarr-support-3.md#checksum-file-format) currently give the first step for checksumming directories as:

> List all immediate child files and directories in JSON objects like `{"path":"foo/bar","md5":"12345...67890"}`.

This implies that the checksum format requires the `"path"` field to come before the `"md5"` field, which I doubt is easy to ensure in all major programming languages.  The checksum format should instead require the fields to be in lexicographic order, i.e., with `"md5"` before `"path"`, for ease of implementation.

**Comment by yarikoptic** [comment]
@jwodder I am a bit confused -- why order should matter at all? isn't it a json dict records which should first be read in full to access their entries, and thus order must not matter.

**Comment by jwodder** [comment]
@yarikoptic The checksum is calculated by taking the MD5 hash of the final JSON structure, so field order is *very* important.

**Comment by waxlamp** [comment]
[`json.dumps()`](https://docs.python.org/3/library/json.html#json.dumps) has a `sort_keys` parameter that would help to solve this problem.

**Comment by jwodder** [comment]
@waxlamp Solve what problem?  The problem here is that the checksum is required to be generated in an order that *isn't* sorted when every reasonable JSON library already has a `sort_keys` option.

**Comment by waxlamp** [comment]
You'll notice I added `bug` and `design-doc` tags to this issue--the problem is solved by changing the text of the design doc along the lines you've already suggested, and updating our own code/plans to make use of the `sort_keys` parameter.

**Comment by yarikoptic** [comment]
> @yarikoptic The checksum is calculated by taking the MD5 hash of the final JSON string, so field order is _very_ important.

gotcha... I wonder if we should get away from "MD5 hash of the final JSON string" to "MD5 hash of the concatenated serialization of `path` and `md5` fields of the record".  This way we 
1. also explicitly state the order
2. do not depend on any formatting
3. could potentially later expand the record with some other useful fields happen we decide to do so (e.g. `size`, `mtime` whatnot)

**Comment by dchiquito** [comment]
I think that using a JSON string is a perfectly valid way to serialize the `path` and `md5` fields. We do not necessarily need to store exactly that JSON object in the `.checksum` file, so we can still include extra data and just require that it be pared down and reserialized to generate the checksum.

**Comment by dchiquito** [comment]
My vote would be to swap the order in the design doc as suggested so it goes `{"md5":"...","path":"..."}`, and fix the implementation as well now while we are still not storing any data.
