### ISSUE TITLE
create: should populate schemaVersion so it is returned along with metadata record for a dandiset

### ISSUE THREAD

**Issue by yarikoptic** [dandi/dandi-api#64]
all metadata records must have `schemaVersion` field defined (ATM the `1.0.0-rc1`, @satra please correct me if I am wrong).

So `create` should define
```
schemaVersion: 1.0.0-rc1
```
ATM

examples are among https://github.com/dandi/dandi-api-datasets.git

**Comment by mgrauer** [comment]
A related issue, how do we define and update what is the current schema version, and coordinate that across the API and the CLI?

**Comment by yarikoptic** [comment]
I would say: define a constant with value `1.0.0-rc1` ATM and then take schema from `https://github.com/dandi/schema/tree/master/releases/{version}` ;-) dandi-api should not introduce changes to the schema.  If any change is necessary -- should be done in `dandi-cli` and then it would re-export automagically into that `/schema` repository.

Also eventually API server should announce which schema version(s) it is expecting (https://github.com/dandi/dandi-api/issues/36).  Then client would first query API server on that, and act accordingly (fail if it can't (outdated) or proceed while uploading metadata in desired by the server schema version if it can)

**Comment by AlmightyYakob** [comment]
Even though this is very similar to https://github.com/dandi/dandi-api/issues/63 I'm going to address it separately, since it's more involved.
