### ISSUE TITLE
dandiarchive/dandiarchive-api images on Docker Hub have stopped automatically building

### ISSUE THREAD

**Issue by jwodder** [dandi/dandi-api#689]
Automatic Docker Hub builds for this repository stopped being triggered for some reason about 15 days ago, and I can't figure out why.

@yarikoptic Were any changes made to the credentials of dandibot (or whatever account was used to set up the repository link)?  Is there a Docker webhook set up in the GitHub repository's webhooks?

**Comment by satra** [comment]
@jwodder - is this not the repo for this: https://hub.docker.com/repository/docker/dandiarchive/dandiarchive-api

**Comment by jwodder** [comment]
@satra Yes, that's the repo.  Note that the three most recent builds (last one four-five hours ago) were manually triggered by me.

**Comment by satra** [comment]
@jwodder - let me see if i can trigger the webhook from the repo to see what's going on.

**Comment by satra** [comment]
appears to be autobuilding again.
