### ISSUE TITLE
Publishing a version produces assets with empty `path`

### ISSUE THREAD

**Issue by jwodder** [dandi/dandi-api#76]
After publishing a Dandiset's "draft" version, listing the assets for both versions produced the following:

<details>
<summary>For the draft version:</summary>

```
[
    {
        "uuid": "4225e110-48e9-41d8-afd0-09aaf4e361bd",
        "path": "subdir/file.txt",
        "sha256": "6fef386efa7208eaf1c596b6ab2f8a5a3583696ef8649be0552ab3effad1e191",
        "size": 19,
        "created": "2021-01-29T17:32:57.516737Z",
        "modified": "2021-01-29T17:32:57.516768Z",
        "version": {
            "version": "draft",
            "name": "Test Dandiset",
            "asset_count": 1,
            "size": 19,
            "created": "2021-01-29T17:32:56.369389Z",
            "modified": "2021-01-29T17:32:56.369426Z",
            "dandiset": {
                "identifier": "000002",
                "created": "2021-01-29T17:32:56.233102Z",
                "modified": "2021-01-29T17:32:56.233136Z"
            }
        }
    }
]
```

</details>

<details>
<summary>For the newly-published version:</summary>

```
[
    {
        "uuid": "4b2fb478-90b7-48f1-946d-31280259606f",
        "path": "",
        "sha256": "6fef386efa7208eaf1c596b6ab2f8a5a3583696ef8649be0552ab3effad1e191",
        "size": 19,
        "created": "2021-01-29T17:32:57.791544Z",
        "modified": "2021-01-29T17:32:57.791607Z",
        "version": {
            "version": "0.210129.1732",
            "name": "Test Dandiset",
            "asset_count": 1,
            "size": 19,
            "created": "2021-01-29T17:32:57.768922Z",
            "modified": "2021-01-29T17:32:57.768952Z",
            "dandiset": {
                "identifier": "000002",
                "created": "2021-01-29T17:32:56.233102Z",
                "modified": "2021-01-29T17:32:56.233136Z"
            }
        }
    }
]
```

</details>

Observe that the asset's "path" field changes from `"subdir/file.txt"` to the empty string.

**Comment by AlmightyYakob** [comment]
It seems like the issue might be with these specific lines:

https://github.com/dandi/dandi-api/blob/8073794937c82a1b2f8f388489581f5c7d56dcce/dandiapi/api/views/version.py#L76-L77

**Comment by satra** [comment]
i'm a little confused here. 

1. why does an asset have a version?
2. why is the id of an asset different between the draft and published versions

**Comment by yarikoptic** [comment]
> i'm a little confused here.
> 
> 1. why does an asset have a version?
> 2. why is the id of an asset different between the draft and published versions

I think current implementation is a bit divergent from an idea of an asset be uniquely identified by uuid.  Related issue/discussion: https://github.com/dandi/dandi-api/issues/71

**Comment by dchiquito** [comment]
I think this is a simple bug with this line: https://github.com/dandi/dandi-api/blob/master/dandiapi/api/models/asset.py#L91
```
class Asset(TimeStampedModel):
    ...
    @classmethod
    def copy(cls, asset, version):
        return Asset(blob=asset.blob, metadata=asset.metadata, version=version)
```
I just forgot to specify `path` in the parameters for the new `Asset`.
