### ISSUE TITLE
Add a staging bucket

### ISSUE THREAD

**Issue by dchiquito** [dandi/dandi-api#85]
Currently unvalidated uploads, draft files, and published files all live in a single bucket.

We should have a "staging" bucket that stores uploaded files, then a separate "public" bucket that stores draft and published files. Because anyone is allowed to upload whatever data they want, this will keep the arbitrary file uploads out of the official public bucket.

This is complicated by the fact that completing a validation is now an asynchronous task that copies blobs between two different buckets. It seems like the S3 and Minio CLIs have methods to do this, but nothing in the official APIs.

This also allows us to store object keys in the public bucket with their sha256 checksums instead of random UUIDs, as after validation, the checksum is known and trusted. Validations must be stored with random values to prevent malicious clients overwriting other blobs.

Implementing this will also involve cleaning up old validations after they are copied.

**Comment by satra** [comment]
i would suggest two different areas of the same bucket. not necessarily different buckets. till we get to solving embargo, everything can be public.

**Comment by waxlamp** [comment]
Closed by #104
