### ISSUE TITLE
Discussion items for next API chat

### ISSUE THREAD

**Issue by satra** [dandi/dandi-api#9]
1. Go through all the API endpoints

2. The relations between REST API and database models. Specifically explore if a single a database table can have both identifier and version as a joint key and how that would be handled in different REST API frameworks.

`/dandiset/:identifier/versions/:version` should lookup an entry/row in a table which matches this pair. the current implementation does this as a set of versions associated with a dandiset effectively as two tables with a one to many mapping.

we should discuss if there is one dandiset table with columns, id, identifier, version, metadata
or two: 
dandiset: id, identifier, versionid 
version: versionid, version, metadata

3. Chat about identifiers (database ids, dandi identifiers, and UUIDs)

**Comment by mgrauer** [comment]
Closing as this has been covered well in our API discussions and implemented.
