### ISSUE TITLE
Mint DOIs upon "release"

### ISSUE THREAD

**Issue by yarikoptic** [dandi/dandi-api#90]
TODOs
- [x] @yarikoptic to provide @dchiquito with details on metadata record and interfacing with datacite (sandbox to be used while developing)
- [x] trigger minting DOI during publish/release of a dandiset and add it as a `doi` field within released dandiset
     - DOI should point to our versioned "permalink" provided by redirector (not web UI URL)

**Comment by yarikoptic** [comment]
- test instance https://doi.test.datacite.org/repositories/dartlib.dandi , so repository is `dartlib.dandi`
- api reference: https://support.datacite.org/reference/introduction and in particular https://support.datacite.org/docs/api-create-dois for minting DOIs
  - there seems to be no token auth, so password needs to be provided, sent via email to @dchiquito and @satra

**Comment by dchiquito** [comment]
For future reference, the prefix for `dartlib.dandi` is `10.80507`.

**Comment by dchiquito** [comment]
Quoting @yarikoptic from https://github.com/dandi/dandi-api/pull/175#discussion_r600006179:
> Also relating to above comment on f'{prefix}/{dandiset_id}/{version_id}' - I did not know that it is legit for suffix (everything after {prefix}/) to contain / . I do see though that there is now DOI 10.80507/000001/0.210323.2052 on that test sandbox instance and according to https://www.doi.org/doi_handbook/2_Numbering.html
> 
> 2.6.3 URN presentation
> 
> To enable the use of DOIs in workflows that have already standardized on URNs, the DOI proxy servers understand the substitution of a colon in place of the initial slash in a DOI name. DOI names may therefore be expressed as URNs in the doi.org domain by writing, for example, the DOI name 10.123/456 in the form https://doi.org/urn:doi:10.123:456. Note, however, that a DOI suffix is allowed to contain other slashes, and where these occur they must be percent-encoded rather than replaced with a colon: for example, the DOI name 10.123/456ABC/zyz would become https://doi.org/urn:doi:10.123:456ABC%2Fzyz, with the final slash character encoded as %2F.
> 
> So may be this "complication" is why typically people avoid using / in the DOI suffixes? E.g. openneuro has 10.18112/openneuro.ds003569.v1.0.0 for https://openneuro.org/datasets/ds003569/versions/1.0.0
> 
> @satra -- are you aware of gotchas with / in the DOI suffix and why it seems generally is avoided?

**Comment by dchiquito** [comment]
I clicked `Publish` on https://gui-beta-dandiarchive-org.netlify.app/#/dandiset/000008 and it successfully created DOI `10.80507/000008/0.210323.2311`.

Can someone take a look the DOI ID+contents and verify that they are what you would expect from the metadata of `000008`?

**Comment by satra** [comment]
@dchiquito - the contents is a great start, but we will want to convert as much as possible to datacite metadata. pinging @djarecka so she can start looking fill in the mapping to datacite fields.

**Comment by satra** [comment]
also currently unable to retrieve this: `curl https://api.test.datacite.org/dois/10.80507/000008/0.210323.2311` returns a 404.

**Comment by yarikoptic** [comment]
does it work for any other DOI on the .test.?

<details>
<summary>not for me</summary> 

```shell
$> curl https://api.test.datacite.org/dois/10.80507/2hfz-sr07
{"errors":[{"status":"404","title":"The resource you are looking for doesn't exist."}]}%  
```
</details>

**Comment by satra** [comment]
i'm assuming the test only serves test dois. there is a normal (non-test) api, which works for existing dois.

**Comment by dchiquito** [comment]
I managed to discover it using 
```
curl --request GET --url 'https://api.test.datacite.org/dois?query=10.80507/000008/0.210323.2311' --user foo:bar
```
It doesn't show up if I remove the `--user` flag, not sure what's up with that.

**Comment by yarikoptic** [comment]
ah here is where the discussion was ;) see #181 re `GET` - may be they need to be not Drafts ;-)

**Comment by waxlamp** [comment]
This is done. Woo hoo!
