### ISSUE TITLE
Server should error when asset assigned metadata with wrong path

### ISSUE THREAD

**Issue by jwodder** [dandi/dandi-api#95]
When a `POST /dandisets/{dandiset_id}/versions/{version_id}/assets/` request is made and the `metadata` field in the request body contains a `path` field whose value differs from the `path` field at the top level of the request body, the server should respond with an error (I believe 400 is the most appropriate status).

See https://github.com/dandi/dandi-cli/issues/368#issue-804701654.

**Comment by satra** [comment]
can someone remind my why path is at the top level?

**Comment by yarikoptic** [comment]
> can someone remind my why path is at the top level?

by `top level` do you mean that there is a `path` column in the table or something else?

**Comment by satra** [comment]
> do you mean that there is a path column in the table

yes

**Comment by dchiquito** [comment]
I think the solution is to remove the requirement from specifying the path on the request body and require it to be set in the metadata instead,

**Comment by yarikoptic** [comment]
> I think the solution is to remove the requirement from specifying the path on the request body and require it to be set in the metadata instead,

sound good to me

re @satra :
> > do you mean that there is a path column in the table
> 
> yes

I believe it is needed to make it feasible to query assets for a given directory -- otherwise you would need to filter through all assets metadata blobs to figure out which ones to list.

**Comment by satra** [comment]
we talked about this as well. internally the table can extract anything from the metadata and put it into a table for efficient query, so `path` should not be a parameter in the POST, but just part of metadata. we will also have to refine the details of the return of GET for each API call before the API is finalized. also that the server will update metadata stored on POST/PUT.

**Comment by yarikoptic** [comment]
gotcha, so it is inline with @dchiquito 's [plan above](https://github.com/dandi/dandi-api/issues/95#issuecomment-776831634)
