### ISSUE TITLE
Staging area proposal

### ISSUE THREAD

**Issue by dchiquito** [dandi/dandi-api#97]
This is a proposal for implementing #85. Things marked in **bold** are deviations from how upload currently works.

You are an API consumer who wants to upload an asset to an existing dandiset. Paths are assumed to look like `{dandiset_id}/{version_id}/{asset_path}` (i.e. `000001/draft/path/to/file.nwb`) because that's what the CLI has been doing so far, but they can be any arbitrary path.

1. Calculate the sha256 of your file.
2. Call `POST /uploads/validate/` with the sha256 **and the path** in the request body. If the sha256 has not already been uploaded and passed validation, the request will fail. You will then need to upload the file through the same multipart upload API, which will return an object key **of the form `uploads/{path}/{uuid}`**. This object is stored in the same bucket as the official draft and published dandiset files. You then call `POST /uploads/validate/` again with that object key as well as the original arguments.
3. Validation runs asynchronously on the server. You check on the progress by calling `GET /uploads/validations/{sha256}/`. If validation fails, alert the user and tell them to restart the process with better data.
4. **When validation succeeds, the blob is copied from wherever it was originally stored to `{path}/{sha256}`. If it was stored in `uploads/{path}/uuid`, it is deleted to avoid keeping duplicates of everything.**
5. You call `POST /dandisets/{dandiset_id}/versions/draft/assets/` with the sha256, asset path, and metadata in the request body. This officially registers the freshly validated blob with the dandiset.

If a file has already been uploaded in dandiset 000001, then someone requests that the same dandiset be uploaded to 000002, this process will validate the data again, then copy it so the same data is stored twice. This is to ensure that the S3 bucket is properly browsable.
We will need to add some potentially aggressive garbage collection for uploads, but that's outside the scope of this issue.

Summary of changes:

* From an external API consumers perspective, the only change is that you need to specify the path when calling `POST /uploads/validate/` so that the server can determine the correct object key to store the blob.
* Initial uploads are now temporary, and are stored with the S3 key `uploads/{path}/{uuid}`.
* Dandiset files are created after validation succeeds, and are stored with the S3 key `{path}/{sha256}`. 

@satra @yarikoptic does this meet all the criteria for publish?

**Comment by satra** [comment]
@dchiquito - why would `path` be in the request body in step 2.

in the ideal world `uploads` are about blobs which could be in any dandiset or even in multiple locations in a given dandiset (however weird and unlikely that may be).

**Comment by dchiquito** [comment]
`path` is included in `POST /uploads/validate/` because at the end of the asynchronous validation process, the validated blob is stored at `{path}/{sha256}` in S3. The validation task needs to know the path so it can copy the object.

The actual process of uploading files still does not need to know anything about the `path`. `/uploads/validate/` is the endpoint which moves a blob out of the `upload` process and into a `dandiset`, so I think it's an acceptable thing to have, although I do see your point.

**Comment by satra** [comment]
>  the validated blob is stored at {path}/{sha256}

i thought the blob would be stored at: `s3://dandiarchive/blobs/{sha256}.ext` (i.e. no relation to a dandiset). is there a reason we are storing blobs at paths? we dropped this in the design for the api to allow for deduplication, which adding path prevents.

**Comment by dchiquito** [comment]
I checked the design doc and didn't see mention of S3 paths, but that rings a bell.

In that case,
* `path` is not longer required in the `POST /uploads/validate/` endpoint. 
* Initial uploads are stored at `dandiarchive/uploads/{uuid}`.
* Validated files are copied to `dandiarchive/blobs/{sha256}`.

@satra Are the extensions necessary for the uuid/sha256 labelled files? Any convenient identifying information has already been obfuscated by removing the file name, so I don't see what storing the extension adds.

**Comment by dchiquito** [comment]
After discussion:
`dandiarchive` is the name of the bucket, uploads go in `uploads/{uuid}` and blobs go in `blobs/{sha256}`.
We should set `Content-Disposition` on the blobs so that they can be downloaded directly from S3. For now we will just ignore any name conflicts from deduplication.

**Comment by yarikoptic** [comment]
re `blobs/{sha256}` - I could be wrong, but I think a flat list might cause some issues one way or another as number of blobs grows.  E.g. it would make impact on some local backups where all those then would go under the same directory.

Why not to establish at least 2 levels of directories from e.g. the first 2+2 (or 3+3) characters of the sha256? e.g. for checksum `d1a44a3537129c375a3225d7c79303eae83e0003edb72ca9e838e6761166da31` it would store it under `d1/a4/d1a44a3537129c375a3225d7c79303eae83e0003edb72ca9e838e6761166da31` ? I do not think that would anyhow add complexity etc, but it should definitely help for those cases of backups etc.  Similar strategy iirc was used by girder and git-annex (although that one is not just using first characters from checksum)

**Comment by satra** [comment]
> it would make impact on some local backups where all those then would go under the same directory.

@yarikoptic  - how would it affect local backups or other use cases? on the s3 itself there is no issue since everything after bucket name is a prefix (i.e key)

**Comment by yarikoptic** [comment]
re extensions: sorry I have missed the chat, I am not certain it is worthwhile adding them since extensions are too weak of an indicator and easy to mislead. file/libmagic should be quite efficient (and we could do that during validation) to deduce typical Content-Disposition from the mime types of the actual content if so desired.

> @yarikoptic - how would it affect local backups or other use cases?

directories with millions of files are not that easy to even regular `ls` (and I guess might effect even overhead from adding a new files into a directory on some if not all file systems), not to say that it would be impossible to get them all into a single git-annex repository if so would be desired.  Having lead directories would make it feasible to compartmentalize into subdatasets or allocate to different backups etc.

**Comment by satra** [comment]
it won't be hard to insert `/` at 3+3 (i think) so if it helps elsewhere let's go for it.

**Comment by dchiquito** [comment]
This was resolved in #104
