### ISSUE TITLE
dandisets_versions_assets_list: remove 'version' record from each and every asset listing

### ISSUE THREAD

**Issue by yarikoptic** [dandi/dandi-api#99]
ATM calling the end point for listing assets would return (identical) `version` field-record for every asset.  Here is an example, although we do have only one asset there ATM ;)

```shell
$> curl -s -X GET "https://api.dandiarchive.org/api/dandisets/000048/versions/draft/assets/" -H "accept: application/json" | jq . 
{
  "count": 1,
  "next": null,
  "previous": null,
  "results": [
    {
      "uuid": "cfe5329d-d2a4-4a34-8b6e-3efc8ee613dd",
      "path": "sub-222549/sub-222549_ecephys+ophys.nwb",
      "sha256": "a3053c0a3d43e949f512aacb7a92b2eae441d513a8df63ce37cc3055f6debff4",
      "size": 590267164,
      "created": "2021-02-09T21:13:43.560178Z",
      "modified": "2021-02-09T21:13:43.560241Z",
      "version": {
        "version": "draft",
        "name": "Allen Oephys",
        "asset_count": 1,
        "size": 590267164,
        "created": "2021-02-09T16:15:20.237068Z",
        "modified": "2021-02-09T16:15:20.237137Z",
        "dandiset": {
          "identifier": "000048",
          "created": "2021-02-09T16:15:20.190109Z",
          "modified": "2021-02-09T16:15:20.190147Z"
        }
      }
    }
  ]
}
```
I would see value from `version` information if I was not already providing dandiset and version in the end point URL , but for listing of the assets for a given dandiset, it is just a waste of bandwidth and would require any client which is eager to just present that information to the user to filter it out.

**Comment by satra** [comment]
when i chatted @dchiquito about this `"version"` key is a misnomer and should have been `isPartOf` - this was introduced by brian for the current state, but we already know which dandiset this is because of the url we are getting this from. so somewhat redundant info for now, but likely to be removed in the future.

**Comment by yarikoptic** [comment]
I think it was resolved at some point
```
$> curl -s -X GET "https://api.dandiarchive.org/api/dandisets/000008/versions/draft/assets/" -H "accept: application/json" | jq . | grep version
  "next": "https://api.dandiarchive.org/api/dandisets/000008/versions/draft/assets/?page=2",
```
and ideally should have been closed by a corresponding PR/commit (attn @dchiquito )
